### ISSUE TITLE
降低档案馆使用门槛

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#1299]
目前档案馆对非专业人士不是特别友好，上万篇文稿有些无从下手。
或许有必要抛弃一部分的中立态度，制作一个引导/推荐阅读文稿目录，将我们认为的真实历史梳理出来。
@PirateBook1

**Comment by banned-historical-archives** [comment]
特别是一些流传很广的被歪曲的历史，群众比较容易产生兴趣。

另外是关于历史人物的评价，我们也可以整理和收集如，历史人物A对历史人物B的评价。

我们应该有足够多的材料支持我们的立场。

**Comment by PirateBook1** [comment]
不是非常急迫，说是“上万”，其实根本没有多少的，而且资料库的使用者应该也没有多少（根据项目 star 数猜的，具体流量没有相关统计部署也说不清楚），接下来一段时间还是继续扩充文稿比较好

关于“中立”态度，档案馆必须要以马克思列宁毛主义作为指导思想，在这个基础上去广泛吸纳文稿。像中马库那样搞就好了，明显的托派网站，但是也不排斥收录斯大林的著作，只是把它们塞到某个小角落

**Comment by PirateBook1** [comment]
我最近在马列毛群众论坛上面发现了一个书单，这个东西我觉得我们可以照搬过来的，我这几天也在录入这些书

**Comment by banned-historical-archives** [comment]
以后使用GPT4写文革综述
