### ISSUE TITLE
求《社会主义政治经济学》（未定稿第二版讨论稿）扫描件

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#1305]
@banned-historical-archives @hubred-rev

求《社会主义政治经济学》（未定稿第二版讨论稿）扫描件。不要广泛流传的那个整理排版过的文字版的。我发现那个有不少错别字，也不利于溯源

**Comment by hubred-rev** [comment]
https://raw.githubusercontent.com/ProletRevDicta/Prolet/master/A%20%E3%80%8A%E7%A4%BE%E4%BC%9A%E4%B8%BB%E4%B9%89%E6%94%BF%E6%B2%BB%E7%BB%8F%E6%B5%8E%E5%AD%A6%E3%80%8B%E4%B8%8E%E3%80%8A%E7%A4%BE%E4%BC%9A%E4%B8%BB%E4%B9%89%E6%97%B6%E6%9C%9F%E7%9A%84%E5%85%9A%E5%86%85%E8%B5%84%E4%BA%A7%E9%98%B6%E7%BA%A7%E3%80%8B/%E7%A4%BE%E4%BC%9A%E4%B8%BB%E4%B9%89%E6%94%BF%E6%B2%BB%E7%BB%8F%E6%B5%8E%E5%AD%A6%EF%BC%881976%E5%B9%B4%EF%BC%89.pdf

**Comment by hubred-rev** [comment]
就是这个

**Comment by PirateBook1** [comment]
@hubred-rev 不行，不是这个扫描件。麻烦查一下这两个文件，我在目前的库里面找不到这两个文件，恐怕已经消失在一千个 commit 之前了
![image](https://user-images.githubusercontent.com/113572850/204543903-8a3e3b86-0f7d-4b66-bdb1-dc64841a5b26.png)

**Comment by PirateBook1** [comment]
你们的整理工作肯定造成了一些文件的丢失

**Comment by PirateBook1** [comment]
已找到
