### ISSUE TITLE
[自动化多媒体录入]《上海工人革命造反总司令部斗争纪要》插图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#1397]
```
{
    archive_id: 7, // 子仓库id(可选)，banned-historical-archives[id]，建议按类型存放，音乐类型为6，插图/图片类型为7
    media: [
    {
        type: 'img',
        name: '《上海工人革命造反总司令部斗争纪要》插图一',
        description: '我们的伟大领袖毛主席',
        source: '《上海工人革命造反总司令部斗争纪要》',
        show_in_gallery: true,
        tags: [{
            type: 'character', // 类型 character, place, subject(主题/事件)
            name: '毛泽东'
        }],
    },
    {
        type: 'img',
        name: '《上海工人革命造反总司令部斗争纪要》插图二',
        description: '上海工人革命造反总司令部成立宣言原件',
        source: '《上海工人革命造反总司令部斗争纪要》',
        show_in_gallery: true,
        tags: [{
            type: 'subject', // 类型 character, place, subject(主题/事件)
            name: '工总司'
        }],
    },
    {
        type: 'img',
        name: '《上海工人革命造反总司令部斗争纪要》插图三',
        description: '1966年11月，毛主席派张春桥同志代表中央文革小组来到安亭',
        source: '《上海工人革命造反总司令部斗争纪要》',
        show_in_gallery: true,
        tags: [{
            type: 'subject', // 类型 character, place, subject(主题/事件)
            name: '安亭事件'
        }, {
            type: 'character', // 类型 character, place, subject(主题/事件)
            name: '张春桥'
        }, {
            type: 'character', // 类型 character, place, subject(主题/事件)
            name: '工总司'
        }],
    },
    {
        type: 'img',
        name: '《上海工人革命造反总司令部斗争纪要》插图四',
        description: '张春桥同志在苏州为工总司队员题词',
        source: '《上海工人革命造反总司令部斗争纪要》',
        show_in_gallery: true,
        tags: [{
            type: 'character', // 类型 character, place, subject(主题/事件)
            name: '张春桥'
        }, {
            type: 'character', // 类型 character, place, subject(主题/事件)
            name: '工总司'
        }],
    },
    {
        type: 'img',
        name: '《上海工人革命造反总司令部斗争纪要》插图五',
        description: '批刻工总司图章和制作袖章的签条原件',
        source: '《上海工人革命造反总司令部斗争纪要》',
        show_in_gallery: true,
        tags: [{
            type: 'character', // 类型 character, place, subject(主题/事件)
            name: '张春桥'
        }, {
            type: 'character', // 类型 character, place, subject(主题/事件)
            name: '工总司'
        }],
    }, {
        type: 'img',
        name: '《上海工人革命造反总司令部斗争纪要》插图六',
        description: '告上海全市人民书原稿',
        source: '《上海工人革命造反总司令部斗争纪要》',
        show_in_gallery: true,
        tags: [{
            type: 'subject', // 类型 character, place, subject(主题/事件)
            name: '一月风暴'
        }],
    }],
}
```
![我们的伟大统帅毛主席](https://user-images.githubusercontent.com/113572850/208713207-30b209ce-8666-4815-be45-6cdc16b42a7e.png)
![上海工人革命造反总司令部成立宣言原件](https://user-images.githubusercontent.com/113572850/208713220-21c8e75d-c3ef-48bb-bf05-1c34f517181c.png)
![QQ截图20221220235606](https://user-images.githubusercontent.com/113572850/208713224-699379b6-bcc6-4483-b032-005f884a3d49.png)
![QQ截图20221220235623](https://user-images.githubusercontent.com/113572850/208713231-21bc510c-ebe9-4bb9-81a6-b60c31adbc09.png)
![QQ截图20221220235632](https://user-images.githubusercontent.com/113572850/208713236-86053d13-4037-4d04-88f7-9d85e62dd4f2.png)
![QQ截图20221220235658](https://user-images.githubusercontent.com/113572850/208713242-03109c4e-fdae-4df0-a543-38ec87d9ebc9.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/e7/e76ea17e-f53a-418c-be68-5a725aad779d.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/a8/a8db5d46-6004-45d5-b22d-dd5a63072008.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/0d/0d8b3e97-c159-4d91-83f4-c199fa6e228a.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/6a/6aa98e24-e62e-4e44-a7d1-6a92070c016b.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/4d/4d4d4af5-e085-49ed-9b6c-66dfd14b81be.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/03/036575e8-eb6e-4d72-9098-1283f349f448.png"%0A]%0A```

**Comment by PirateBook1** [comment]
@banned-historical-archives source 这一项并没有在前端显示
