### ISSUE TITLE
我为什么参加红色造反团 毛远新1966年12月11日的大字报

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#167]
![1](https://user-images.githubusercontent.com/110591488/183345601-3c79f140-5e5a-4607-9f8b-3334f9350370.jpg)
![2](https://user-images.githubusercontent.com/110591488/183345595-2e3bc05d-64c9-4081-9e6a-ba19d112c8ff.jpg)

**Comment by PirateBook1** [comment]
我为什么参加红色造反团

毛远新

我是军工六〇级的事业学员，在连队当兵半年后，经过自己申请，上级批准回院参加文化大革命，回来和同志们一起革命，一起造反，造走资本主义道路当权派的反，也造自己思想里资产阶级反动路线遗毒的反，造各人私心杂念的反。

九月初回到学院，做了一些调查研究，参加了不少活动，对文化革命有了初步理解，是造反团的小将们教育了我，鞭策了我，也是八八团部分同志从另一方面教育了我，开始认识到思想里有许多错误，对自己进行了批判，在这里交给大家，请同志们进一步批评和帮助。

我是怀着青年人朝气蓬勃的雄心壮志，怀着对人民解放军深厚的感情踏进军工大院的。我是干部子弟，年年学习成绩优良，有一定工作能力，思想认识水平也“较高”，一直担任班长、党小组长，评三好、五好、优秀党员从来没有拉下过我；领导上，同志们夸奖我，颂扬我，吹捧我，似乎很不错了。现在看起来正是这些东西也害了我，是学院资产阶级反动路线深深地毒害了我，同时又利用我去执行过错误路线，害了别的同志。刘居英、戴其萼等人利用我小资产阶级知识分子的虚荣心，骄傲自满情绪，投我所好，拼命吹捧我，给我灌输了大量毒素，而又使我不察觉，使我这个学员干部学会了一套错误路线的思想和工作方法，从而让我不自觉地让其利用，抬高他们，压制别人，成了反动路线的牺牲品。

对过去，不应该否定一切，我六年来，在主席思想的教育下，在同志们的帮助下，主流还是好的，辛辛苦苦为群众做了不少有益的工作，对同志也做过大量正确的好的思想工作，取得一定成绩，得到同志们的信任。自我思想改造也有不少进展，虽然步子小些，但还是前进的。这是主席思想和资产阶级思想争夺青年的斗争，因为长期处于在这个大染缸里，中毒不少，可以三七开吧。

几年来我确实为领导整过不少人的黑材料，抓住别人的毛病，偷偷向支部汇报，有时先定了框框再有选择地收集某人的材料；平时不开展正当的批评自我批评，到了运动就抓小鬼，新帐老帐一起算。特别是六四年反不良倾向运动，整过班里几个人，甚至组织过班里斗争会斗争过“不听招呼”的党员；在党小组会上伙同上级干部竟把某人定为反党性质。同时又利用那些“好同学”监视“差的”，收集“差的同学”的情况。对那些“爱发牢骚，调皮捣蛋”的同学，有机会总想把他们整老实不可。

等等做法，确实以为自己对党忠诚，对党的事业负责任，体现了自己是党的驯服工具。现在我认识到了，除了那些正当的群众思想工作和正确的组织汇报外，这种“工作能力”是个什么货色。

这一套东西是从那里来的呢？其一，学院长期资产阶级教育路线的结果，其二，个人私心杂念在作怪。我确实对党组织一片忠心，拼命想为党多做些工作，对这套做法毫不怀疑，认为是天经地义的，执行上级东西就是要不折不扣，无论对错，都能从“对”的角度来理解，即使上级错了，那时上级的责任，我忠实执行了，问心无愧。宁可政治路线上犯

了，“自己解放自己”战斗团出现了，尽管他们有些不合实际的想法，但人家提出了一个很好的东西，即造反团不要老想改造人家，要把活学活用主席著作，加强自己的思想改造提到主要地位上来，否则你以这样的思想水平，根本不可能把资产阶级反动路线批透。但有人就听不入耳，把人家臭骂一通。这样下去造反团就要僵化了，要停滞不前了。造反就可能转向其反面保守了，我是深有教训的。这就是当前团内出现右倾保守思想的根子，决不是什么“政策策略讲多了”，什么“攻八八团太少了”等等。要解决这个问题是全团性的思想工作，主要原因不是什么总团某负责人的右倾保守。有人把自己的思想认为是无可指责，大反别人右倾，但一到斗争的关键却怕得要死，千方百计保自己团，比如对苏晓光、对三十多个受迫害的工人，都反映了这种情绪，而当局势稍稳，又利用什么“首都造反派”的代表把造反团、潘复生吹捧一番，吹得某些人心里热呼呼的，接着就要把矛头指向八八团一个革命群众团体。

造反团的同志们，目前形势发展到一个新的阶段，只凭“造反有理”一股劲猛冲是不够的了，现在要造反到底，又要掌握稳政策，既要猛打猛冲，又要善于运用斗争的策略，如果再不加强团内主席思想的学习、政策的学习，团内思想水平已不能满足斗争的需要。可以为什么运动前期的造反团骨干学员从北京从外地回来后都大讲政策策略，讲艰苦的思想工作，而开始的落后一步的干部和教员却大反“右倾”，以极“左”的面目出现反对这些学员呢，是学员右倾了，还是你们又落后一步了呢？请大家思考一下。

一句话，我们多数还是小资产阶级知识分子世界观为主的思想，如果再不进行艰苦的自我思想改造，破“私”立“公”，革命性是不彻底的；对斗争的长期性复杂性是缺乏轫性的；在组织上就会不能团结大多数群众，搞孤家寡人政策，单兵独马的策略，搞个人风头，宗派主义、关门主义。特别提醒团内中毒较深的同志，这样下去，彻底进行革命的重担造反团是担不起的。

学院里还有相当一批干部，至今还忧虑重重，有的满腹怨气，有的不偏不倚，貌似公允，不敢有鲜明观点，美其名曰“具体问题具体分析”。请问这些我过去的老首长，老教员们，我们过去做的错事，八八团前期跌的交子，不正是你们直接精心栽培的结果吗？不正是你们言传身教教出来的吗？运动前期不是你们最积极的执行错误路线吗？当前造反团不给你们算账，把矛头指向党委，已经够宽厚的了。还有什么气出不来呢？我说责任主要在李范五、刘居英，你们就没有一点错误吗？上推党委、下推八八团，你们就清白了吗？为什么毛主席讲了几十年相信群众、依靠群众，尊重群众首创精神，你们听不进，可省委、院党委的指示却接受那么快，执行那么得力呢？这不说明你们对上面的东西具有选择性吗？符合自己利益的接受，不符合的选掉。正是那些指示和你们脑子里的“私”字共鸣，你们才如此合拍的。

我们的家长，广大的工人、贫下中农、革命先烈，把自己的儿女交给你们培养，难道他们希望你们用自己满脑子的错误思想，把这些青年培养成复辟旧社会的工具吗？扪心自问，这是多大的罪恶啊！正是这次毛主席亲自发动的文化大革命，挽救了我们也挽救了你们，你们还有什么权力怨天怨地呢？还是放下臭架子到群众中来吧，狠触自己灵魂深处的“私”字和我们一起把革命进行到底吧！只要你们能深刻检查错误，能够彻底揭发批判院党委，广大群众会热烈欢迎你们的。你们不少人过去在枪林弹雨里出生入死，很多人至今还留着伤疤，你们不少人兢兢业业为党做过很多工作，为什么现在都怕得要死，陷在“私”字里跳不出来了。赶快行动吧，否则革命群众将决定对你们的取舍。

以上谈了自己的看法，向同志们交了心，有道理的请同志们思想，错误的希望大家批判，我过去没有学好主席思想，特别愿意在这场史无前例的大革命中和同志们一起学好用好，同时也建议同志们到社会上去和工农群众一起学好用好主席思想，只要我们思想提高了，对资产阶级反动路线的批判，对自己头脑里的“私”字的批判才能批倒、批透，文化大革命才能进行到底。

一九六六年十二月十一日

哈军工红色造反团驻沪《红色造反》战斗队印
苏州市纺织工人革命委员会翻印
1967.1.11

**Comment by PirateBook1** [comment]
@banned-historical-archives 这份可以用来实验无需 OCR 直接提供文字的情况
