### ISSUE TITLE
希望定期导出索引以及静态html文件

### ISSUE THREAD

**Issue by moe-rika** [banned-historical-archives/banned-historical-archives.github.io#1710]
NodeJS不是每台计算机都预先安装了。
希望隔一段时间就做个release。
https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/204

**Comment by moe-rika** [comment]
如果考虑SEO的问题可以将标题与url导出。

**Comment by moe-rika** [comment]
books.ts会不会越来越大导致加载变慢？

**Comment by PirateBook1** [comment]
肯定是会的，book.ts 里面的文稿越多导入数据库的时候就越慢

**Comment by banned-historical-archives** [comment]
books.ts可以拆分，到时改成从文件中读取，这样也避免了合并冲突。

另外books.ts不影响前端性能，只是构建html的时候要用到

**Comment by banned-historical-archives** [comment]
SEO已经做了，构建后会生成sites.xml，每个静态html也设置正确设置了title和meta信息，但谷歌不会完全收录，原因不明

**Comment by banned-historical-archives** [comment]
https://github.com/banned-historical-archives/banned-historical-archives.github.io/tree/gh-pages

自动构建的html静态文件在这个分支，你看够不够用？还是需要更细粒度的html？

**Comment by banned-historical-archives** [comment]
索引也在gh-pages分支。

https://banned-historical-archives.github.io/_next/data/euca0R_5qz5meDHBAl-zi/articles.json
