### ISSUE TITLE
制定校对规范

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#187]
1. 许多文章中简体繁体混用，校对时/预处理时是否需要强制转换为简体，还是与原文保持一致？我觉得为了便于检索统一改为简体较好，除非个别地方使用简体会丢失重要信息。
2. 标点符号的标准，统一使用全角符号？
3. 字母，数字，大写数字的标准，比如英语单词与中文之间所否需要空格，阿拉伯数字与中文之间所否需要空格，大写数字是否使用廿卄卅卌，大写数字的零有很多种表达方式（○〇零），是否需要统一?正文中的提到的日期是否需要统一格式(1930/1/1，1930.1.1，一九三〇年一月一日)？

**Comment by 106coup** [comment]
粗略想了一些：
1. 应当全部使用简体。
2. 统一使用全角吧。
3. 从美观角度来看英文、阿拉伯数字与中文间有空格比较好；大写数字的问题以原文为准吧；零的问题建议用这个“〇”；正文的日期，如果是用于标记文稿日期的（标题下面出现的），应当用“一九三〇年一月一日”这种形式，正文内部的以原文为准。

**Comment by banned-historical-archives** [comment]
像一些讲话记录，时间日期需要定一个规范，没有真正的原文可以参考（可能每个记录者习惯不同）

**Comment by 106coup** [comment]
你指的是这个时间还是？
![image](https://user-images.githubusercontent.com/110591488/184293401-e10b9e78-626b-4ff3-a5bf-486847c1c805.png)

正文的时间怎么原文如何实际就照录好了。如果有些偏差也无碍吧？

**Comment by banned-historical-archives** [comment]
原文可能有差异，讲话记录不一定是同一个人记录的。不同来源可能有差异。

**Comment by banned-historical-archives** [comment]
这个问题也不大，我想统一规范后便于正文对比。

**Comment by 106coup** [comment]
这个问题不大，对照阅读的读者也不会去在意日期的偏差。实在要统一的话我倾向于用汉字。
