### ISSUE TITLE
文稿命名规范

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#190]
1.文稿合辑如何处理?
可能来源A中命名为“B+C”或者“某某在11月份的讲话”的文稿中包含两篇子文稿B和C；来源D和E分别包含了B、C文稿

按照现在的文稿id计算方法，A中的文稿将被视为独立的文稿，无法将A中的B与D中的B进行对比。

2.文稿来源命名问题
许多未知来源的文稿，这些来源如何命名？其中一些文稿可能出自同一本笔记，是否需要将他们归为一类，比如A和C都来源于“未知手稿2”

3.文稿命名问题
3.1.非正式文稿的标题如何确定
有些讲话记录，可能记录者不同，在标题上有些差异
3.2.文稿重名如何解决冲突
虽然目前使用 标题+作者+时间 来生成文稿id，但还是有许多文稿无法生成唯一id（可能因为缺时间或作者）

4.后期维护问题
一旦改变标题，文稿的id就会变更，不仅影响链接OCR补丁文件也受影响，如果考虑到（1）中的联动问题就很复杂了。子文稿独立出来是最理想的。

**Comment by 106coup** [comment]
1. 文稿合集问题，最好是把单独每篇拆出（最细到哪一次讲话）对应
2. 文稿来源，如果两份材料不是明显标记了出自同一份，那就把它们看作两份独立的材料。
3. 标记“来源一”、“来源二”？
4. 具体的技术实现问题需要你再仔细妥当考虑。

**Comment by banned-historical-archives** [comment]
我准备这样做：
讲话记录如果不同记录者标题不同则随便取一个，来源都改为
xxx在x年x月x日的讲话
同一天可能有多次讲话，如果发生这种情况再加后缀1234

**Comment by 106coup** [comment]
可以

**Comment by 106coup** [comment]
还有一个值得商榷的问题就是文章类型和标签的问题。

![image](https://user-images.githubusercontent.com/110591488/184296548-06451ee6-d250-4cda-bd78-61d9b3240bc6.png)
![image](https://user-images.githubusercontent.com/110591488/184296777-b0c63a0b-9f6a-46df-9896-8eabb3ee64be.png)

这个东西实在是有点主观，“大联合”、“造反运动和派别斗争”这类标签尤甚。

**Comment by banned-historical-archives** [comment]
子文稿独立是个体力活，现在没办法自动地判断是子标题还是子文稿以及哪些部分属于子文稿，还有时候没有明显的界限（比如包含多人的讲话稿）。
有些情况独立不独立都有它的道理，像一些讲话记录，有些人是按讲话人去记录，有些人是按事件去记录（里面包含多个讲话人的讲话）。
我想先不管这么细了，到时加个“关联文稿”算了，怎么合并，怎么拆分到时再说吧。

**Comment by banned-historical-archives** [comment]
标签现在大部分是从文革文库第一版中拿过来的，其他的就是简单分析一下标题关键词得出的，以后可以分析正文内容打标签。
我试过 paddle LAC，只能提取一些关键词出来，不能用一些抽象的词（可能在正文中没有出现过）概括整篇文章，所以效果不太好。

**Comment by 106coup** [comment]
子文稿独立这件事还是每个资料具体分析吧，讨论一下看看怎么分。比如之前那份毛远新论民兵问题的分开比不分开好。

**Comment by banned-historical-archives** [comment]
@106coup 我说的是这种情况，这篇文稿分开比较好？
https://banned-historical-archives.github.io/articles/5eb9517882/

**Comment by 106coup** [comment]
每篇文稿具体分析吧，像这篇目前标注多个日期的处理办法我觉得已经可以了。
