### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第一章插图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#1960]
```
{
    archive_id: 7, // 子仓库id(可选)，banned-historical-archives[id]，建议按类型存放，音乐类型为6，插图/图片类型为7
    media: [
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图一',
        description: '克伦威尔',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二',
        description: '利尔本在法庭上',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图三',
        description: '瓦特发明的第一台蒸汽机',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图四',
        description: '十九世纪初英国的煤气工厂',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图五',
        description: '女工下矿井',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },{
        type: 'img',
        name: '《简明世界史（近代部分）》插图六',
        description: '童工在矿坑里劳动',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },{
        type: 'img',
        name: '《简明世界史（近代部分）》插图七',
        description: '民兵——“一分钟人”纪念像',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图八',
        description: '列克星屯的战斗',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    ],
}
```
![QQ截图20230122220821](https://user-images.githubusercontent.com/113572850/213920288-fb45cd36-f625-4ebf-9cf6-c335faecaac2.png)
![QQ截图20230122220855](https://user-images.githubusercontent.com/113572850/213920334-d8b35a50-8bd7-4bf7-8c89-1a0975dff07c.png)
![QQ截图20230122220925](https://user-images.githubusercontent.com/113572850/213920382-05a19794-ec26-4909-be93-22ff52f757e9.png)
![QQ截图20230122221000](https://user-images.githubusercontent.com/113572850/213920386-df334ae0-3d57-409c-a7f8-02d10f5cf231.png)
![QQ截图20230122221022](https://user-images.githubusercontent.com/113572850/213920389-2d30b2c0-8fd5-48f8-904a-f8f4b002ab1f.png)
![QQ截图20230122221042](https://user-images.githubusercontent.com/113572850/213920392-afcf0a2c-ff94-4868-8bc6-9d91d5d661a2.png)
![QQ截图20230122221117](https://user-images.githubusercontent.com/113572850/213920393-d7b8ab86-df14-42d0-a16c-6fe393f62a79.png)
![QQ截图20230122221140](https://user-images.githubusercontent.com/113572850/213920394-d6ac3b3b-604a-42ce-80d7-461cddc13941.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/04/047608ad-5320-45a7-9105-5eb07181e1c7.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/87/870bf54d-70f0-41b8-8e58-cebf816e43cc.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/5e/5e42b82c-1b42-47d4-bbfa-f0726ca25eff.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/92/92d121b5-217c-45ee-8055-11eb0ecae439.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/13/13360cec-9769-4e89-bd60-d2583c8b7d97.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/a1/a1501469-5a58-4582-ab20-1026ea017a5b.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/66/6667e1b4-7b89-4b13-a8a6-052391322180.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/d3/d319899f-acfa-4439-8f5a-a8336586b4de.png"%0A]%0A```

**Comment by PirateBook1** [comment]
@banned-historical-archives 这个第一章还没整完
