### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第二章插图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#1999]
```
{
    archive_id: 7,
    media: [
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图九',
        description: '罗伯斯比尔',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十',
        description: '马拉',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十一',
        description: '巴贝夫',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十二',
        description: '西班牙人民反抗拿破仑的侵略',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    ],
}
```
![1](https://user-images.githubusercontent.com/113572850/214779455-c89dbe95-e08a-44db-9b32-fd3408b22117.png)
![2](https://user-images.githubusercontent.com/113572850/214779466-5a4ae08a-633c-4719-851e-65562a5d7599.png)
![3](https://user-images.githubusercontent.com/113572850/214779468-3ad74b1a-5e25-4e69-abae-eb91bd2ac87c.png)
![4](https://user-images.githubusercontent.com/113572850/214779471-e42d8bc7-f528-4ec8-8737-ea14f4c3d5a3.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/d1/d15d9897-46bf-44b0-937b-2800fc01df57.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/be/bebdd5a4-f34f-4b37-b542-27642fe0b9db.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/dc/dcf7fd56-c1ba-4dd4-a874-a21f5838a847.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/92/928525db-7944-4bf9-9b79-49ca8e9ad1d1.png"%0A]%0A```
