### ISSUE TITLE
有没有不依赖于nodejs的html文件下载（不提供比较功能也可以）

### ISSUE THREAD

**Issue by moe-rika** [banned-historical-archives/banned-historical-archives.github.io#204]
我暂时只在public文件夹里面找到了数据库文件，但是是一些二进制文件。

**Comment by moe-rika** [comment]
看来只有文化大革命文库是这种情况。

**Comment by banned-historical-archives** [comment]
这个数据库文件来自ProletRevDicta 文化大革命文库压缩包，这个压缩包应该是从文化大革命文库光碟中拷贝出来的。为了便于溯源，我保留了数据库原始文件。

**Comment by banned-historical-archives** [comment]
为什么要导出html？你想二次加工可以从数据库中导出（指构建以后的数据库，包含文化大革命文库数据库）。

**Comment by banned-historical-archives** [comment]
https://github.com/speechfree/cultural-revolution-database

可能你要找的是这个

**Comment by banned-historical-archives** [comment]
https://github.com/banned-historical-archives/banned-historical-archives.github.io/tree/gh-pages

本仓库的html在这个分支
