### ISSUE TITLE
技术人员贡献代码相关问题询问

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#205]
```
$ npm run dev
$ npm run dev:ocr-server
```

输入第一句之后出现以下报错，请问这是怎么回事？
![image](https://user-images.githubusercontent.com/113572850/190334845-1f17ef99-b122-43cd-8c6d-b34cc6fa4d82.png)

我正在编写[这篇资料](https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/123)的代码。

**Comment by banned-historical-archives** [comment]
可能windows上有这个问题，
你把第一句 npm run dev换成 npx next dev

**Comment by banned-historical-archives** [comment]
已经更新文档

**Comment by PirateBook1** [comment]
@banned-historical-archives 
![image](https://user-images.githubusercontent.com/113572850/190392743-5bd9367f-b91b-4251-9223-24feba13a907.png)
这种情况是不是一张得分隔成两张，怎么操作呢

**Comment by PirateBook1** [comment]
我解析数据库这步也失败了……
![image](https://user-images.githubusercontent.com/113572850/190397965-6be55a8a-df82-4280-9a14-1612760c43de.png)

**Comment by banned-historical-archives** [comment]
mysql安装了吗？数据库的配置是按文档中设置的吗？

**Comment by PirateBook1** [comment]
@banned-historical-archives 能不能再详细讲讲 MySQL 建表后怎么设置那些参数，给点资料也行……本人在数据库与后端方面纯小白，完全没接触过

![image](https://user-images.githubusercontent.com/113572850/190471323-97e11813-a048-4bd7-9b10-8e169953d3bd.png)

以及建表之后这步怎么把 Node.js 连接上数据库……

```
npm run init-db
```

**Comment by banned-historical-archives** [comment]
mysql帐号密码正确且mysql服务开启才能连上，如果图形化客户端能使用就说明mysql服务是正常的

**Comment by PirateBook1** [comment]
@banned-historical-archives 目前的报错：
```
npm run init-db
```
这步之后的报错：
![image](https://user-images.githubusercontent.com/113572850/190645595-9cebc704-70e0-4d2e-80a5-767d0a42afd8.png)

在本地测试新添加的图片集之后的报错：
![image](https://user-images.githubusercontent.com/113572850/190645865-8a6ea281-aeda-4545-9b0d-fd90d04f6b85.png)

**Comment by PirateBook1** [comment]
其他步骤已经确认成功了，目前进行到这步
```
npm run dev:ocr-server
```

**Comment by banned-historical-archives** [comment]
你试试cnocr能单独运行吗？看看他们的官网

**Comment by PirateBook1** [comment]
@banned-historical-archives CnOcr 确认可以运行了，已经可以在线调试 OCR，目前的问题还是这句：
```
npm run init-db
```
![image](https://user-images.githubusercontent.com/113572850/190853065-4feb7aed-cc4a-4d43-966d-62c3556e517b.png)
在读这份资料时不知为何返回了一个 undefined 回来，导致进程卡死

**Comment by banned-historical-archives** [comment]
看看你books.ts修改的地方？

**Comment by PirateBook1** [comment]
@banned-historical-archives 
![image](https://user-images.githubusercontent.com/113572850/190858068-bf1b0361-b12c-43ee-b137-8d7536edb5d7.png)

**Comment by banned-historical-archives** [comment]
好的，看起来没问题，可能是zhangchunqiao10.parse里面的问题。
会操作git吗？你提交到你的分支上看看？
或者你用vscode断点调试一下，修改backend/debug.ts，把id改成zhangchunqiao10

**Comment by PirateBook1** [comment]
这时 zhangchunqiao10 的代码，完全复制的 zhangchunqiao5
```
import { join } from 'path';
import { existsSync, writeFileSync, readFileSync } from 'fs';
import ocr from '../ocr';
import {
  ContentPart,
  ContentPartRaw,
  ContentType,
  Date,
  OCRResult,
  ParserOption,
  ParserResult,
  Pivot,
  TagType,
} from '../../types';
import { merge_to_lines } from './utils';

const opt = {};

type PartRaw = { page: number; x: number; merge_up?: boolean } & ContentPartRaw;
function extract_parts(ocr: OCRResult[], page: number): PartRaw[] {
  const res: PartRaw[] = [];
  for (let i = 0; i < ocr.length; ++i) {
    let text = ocr[i].text.trim();
    const x = ocr[i].box[0][0];
    res.push({
      page,
      text,
      x,
      // type: /[:：]$/.test(text)
      //   ? ContentType.appellation
      //   : ContentType.paragraph,
      type: ContentType.paragraph,
    });
  }
  const paragraphs = res.filter((i) => i.type === ContentType.paragraph);
  for (let i = 0; i < paragraphs.length; ++i) {
    const last = paragraphs[i - 1];
    const next = paragraphs[i + 1];
    const t = paragraphs[i];
    if (page === 5 && t.x > 200) {
      t.merge_up = false;
      continue;
    }
    if (last && last.x < t.x && t.x - last.x > 30) {
      t.merge_up = false;
    } else if (next && next.x < t.x && t.x - next.x > 30) {
      t.merge_up = false;
    // } else if (last && /[:：]$/.test(last.text)) {
    //   t.merge_up = false;
    } else {
      t.merge_up = true;
    }
  }
  return res;
}

function merge_parts(parts: PartRaw[]): ContentPart[] {
  const res: ContentPart[] = [];
  for (let i = 0; i < parts.length; ++i) {
    if (
      parts[i].merge_up &&
      res[res.length - 1].type === parts[i].type &&
      !/[:：]$/.test(res[res.length - 1].text)
    ) {
      res[res.length - 1].text += parts[i].text;
    } else {
      res.push({
        type: parts[i].type,
        text: parts[i].text,
      });
    }
  }
  return res;
}

export async function parse(
  imgPath: string,
  parser_opt: ParserOption,
): Promise<ParserResult[]> {
  const parts: PartRaw[] = [];
  for (
    let i = parser_opt.page_limits[0][0];
    i <= parser_opt.page_limits[0][1];
    ++i
  ) {
    const path = imgPath.split('/public/books/')[1] + '/' + i + '.jpg';
    const ocrResults = merge_to_lines(
      (await ocr({ img: path, resized_shape: 2388 })).filter(
        (i) =>
          i.text.trim() &&
          !/^[-\w\d—“"一行发卡\.·，]+$/.test(i.text.trim()),
          // 去页码
      ),
      30
    ).sort((a, b) => a.box[0][1] - b.box[0][1]);

    // 去掉标题和日期
    parts.push(...extract_parts(i === 3 ? ocrResults.slice(1) : ocrResults, i));
  }

  const articles: PartRaw[][] = [];
  parts.unshift({
    text: '张春桥同志十月十六日的重要报告',
    type: ContentType.title,
    x: 0,
    page: 1,
  });
  for (let i = 0; i < parts.length; ++i) {
    if (parts[i].type === ContentType.title) {
      articles.push([]);
      while (parts[i].type === ContentType.title) {
        articles[articles.length - 1].push(parts[i]);
        ++i;
      }
      --i;
      continue;
    } else {
      articles[articles.length - 1].push(parts[i]);
    }
  }

  const res: ParserResult[] = articles.map((article) => {
    const merged_parts = merge_parts(article);
    const title = merged_parts[0].text;
    merged_parts[0].text = title;
    return {
      title: '张春桥在上海市革命委员会报告会上的讲话',
      alias: title,
      parts: merged_parts,
      authors: ['张春桥'],
      dates: [
        {
          year: 1967,
          month: 10,
          day: 16,
        },
      ],
      is_range_date: false,
      comments: [],
      comment_pivots: [],
      description: '',
      page_start: article[0].page,
      page_end: article[article.length - 1].page,
    };
  });
  return res;
}
```

**Comment by PirateBook1** [comment]
@banned-historical-archives

**Comment by banned-historical-archives** [comment]
修改backend/debug.ts，把id改成zhangchunqiao10
然后在zhangchunqiao10这行加上断点
 const ocrResults = merge_to_lines(

在vscode中按f5就可以debug了

到断点时检查一下path,imgPath是否正常

**Comment by PirateBook1** [comment]
@banned-historical-archives 我已经推到我的分支里面了，你可以帮忙看看

**Comment by banned-historical-archives** [comment]
应该是windows特有的问题，windows下获取的路径用的是反斜杠，我在最新代码中已经强制转成forward slash，你更新一下试试

**Comment by PirateBook1** [comment]
@banned-historical-archives 还是不行，报了一模一样的 undefined
![image](https://user-images.githubusercontent.com/113572850/190867876-0ba0934a-69cc-4d81-975f-4a4fa2a873ef.png)

**Comment by banned-historical-archives** [comment]
我有个地方忘记改了，现在再更新代码试一下

**Comment by PirateBook1** [comment]
@banned-historical-archives 最新更改还是不行，报空

**Comment by banned-historical-archives** [comment]
那只能麻烦你打断点调试一下了

**Comment by PirateBook1** [comment]
@banned-historical-archives 这次断点怎么打，还是像你之前说的打在 zhangchunqiao10.ts 吗

**Comment by PirateBook1** [comment]
@banned-historical-archives 一些可能有用的信息：
![image](https://user-images.githubusercontent.com/113572850/190893753-f20c633e-8bde-408d-9d84-e49f7ec67639.png)
程序在这行抛出错误：
![image](https://user-images.githubusercontent.com/113572850/190893977-d36ec40d-3e9f-43b3-aa6f-1a01563271ca.png)
path 和 opt 的状态：
![image](https://user-images.githubusercontent.com/113572850/190894017-2a2090ba-53ff-4564-b6e0-b20e7b9db5b7.png)

**Comment by PirateBook1** [comment]
@banned-historical-archives 当前的代码是这样的：
![image](https://user-images.githubusercontent.com/113572850/190896634-5dd9800f-14b3-4871-b9ac-8a02e35c94f9.png)

**Comment by banned-historical-archives** [comment]
再拉一下最新代码试一下？

**Comment by PirateBook1** [comment]
@banned-historical-archives 终于可以了，目前一切正常

我还对校对流程有些疑惑，比如说我新增加的这篇 zhangchunqiao10：
![image](https://user-images.githubusercontent.com/113572850/190901949-92415b33-b5a5-4f12-9630-343f51d0aaed.png)
我能不能直接在本地校对，然后校对过一遍了再推上来，我刚刚看了看那个 /patch 目录那里应该是校对补丁的位置

还有能不能教一下怎么解决段落错误的问题，你也看到了这篇文章基本上没有一处段落是正确的

**Comment by PirateBook1** [comment]
如果段落问题我无能为力和不能本地校对的话我就直接添加原图片文件、对应 .ts 和修改 book.ts 后就推上来合并了

**Comment by banned-historical-archives** [comment]
本地没有简单的方式直接校对。另外首先要保证段落没有错误才能校对，这个比较复杂，要分析ocr的结果，去掉噪声，总结大致的段落规律。你可以看看其他文稿是怎么处理段落的。
可以先推上来，我再处理。

**Comment by PirateBook1** [comment]
@banned-historical-archives 这 Actions 转了三小时了还没开起来，是不是出新 bug 了
![image](https://user-images.githubusercontent.com/113572850/191022739-fdaa1bd4-31dc-436b-9146-560254a96942.png)

**Comment by banned-historical-archives** [comment]
因为这个pr 缺了新增图片的ocr_cache https://github.com/banned-historical-archives/banned-historical-archives.github.io/pull/207

**Comment by PirateBook1** [comment]
@banned-historical-archives 怎么解决呢

**Comment by banned-historical-archives** [comment]
执行 init-db （有点慢）或者你在debug.ts 里面跑一下新增的内容

**Comment by PirateBook1** [comment]
@banned-historical-archives 关于手写稿的录入，比如 wanghongwen5.ts 这类文件模板恐怕你还得再改改。手写稿件目前没有提供变量来分别存放 title 和 text

**Comment by banned-historical-archives** [comment]
zhangchunqiao12.ts呢？

**Comment by PirateBook1** [comment]
@banned-historical-archives 把第 21 行这个 text 换成字符串就行了是吧

![image](https://user-images.githubusercontent.com/113572850/191476667-03c06f16-afa1-43dc-a91f-e082803014ba.png)

**Comment by banned-historical-archives** [comment]
不用改21行，改19行就行了

**Comment by PirateBook1** [comment]
看明白了，book.ts 里面的 name 指来源里面的名字，parser 里面的 text 是正文大标题，里面的 title 是显示在左上角“标题”这里的（可能有别名）

**Comment by banned-historical-archives** [comment]
对

**Comment by banned-historical-archives** [comment]
title一般是最正式名称，用来判断是否为同一篇文稿的依据之一，用于文稿对比。别名的话需要特别指定alias。
录入前搜索一下有没有存在同一篇文稿，如果设置相同的title就作为不同来源录入进去，如果新增的文稿标题与它不完全一致就需要填写alias。

**Comment by PirateBook1** [comment]
@banned-historical-archives 又开始报错了……
![image](https://user-images.githubusercontent.com/113572850/194688724-af7fd100-51d1-4f60-bbc9-d2f17cc62719.png)

**Comment by banned-historical-archives** [comment]
上个月改过这个地方，可能要把数据库表都删了再跑

**Comment by PirateBook1** [comment]
@banned-historical-archives ocr.ts 第 72 行 python3 改成 python 才能运行，不知道问题出现在哪。这么改你那边应该能跑吧

**Comment by PirateBook1** [comment]
对于这种稿件我暂且是直接 ocr 后 push 上来然后用你写的程序在前端改吧

**Comment by banned-historical-archives** [comment]
这个ocr工具先不用吧，很快自动化文稿录入可以使用了

**Comment by PirateBook1** [comment]
@banned-historical-archives 那我这边先停工了，等你把功能做完

**Comment by PirateBook1** [comment]
@banned-historical-archives 如果我要改一份文稿的 ID，是改这三处吗

![image](https://user-images.githubusercontent.com/113572850/194812364-8a64e2ae-0681-4d6c-bcb7-842761317a9f.png)
![image](https://user-images.githubusercontent.com/113572850/194812481-72e4c2d4-63b6-489c-8e49-16f6a29871b2.png)
![image](https://user-images.githubusercontent.com/113572850/194812725-88e8aff2-eecf-45f2-8a64-b1abf4085a99.png)

**Comment by banned-historical-archives** [comment]
@PirateBook1 还有patch/articles目录下 含有sirenbang1的文件

**Comment by PirateBook1** [comment]
@banned-historical-archives 所以现在是这样一个流程吗：填写 issue -> 自动 OCR（不分质量好坏）后 pull request -> 部署完毕后人工修改段落校对

**Comment by banned-historical-archives** [comment]
对

**Comment by PirateBook1** [comment]
子模块上传路径最好自定义一下，总不能今后的全部文稿都扔到 archive1 里

**Comment by banned-historical-archives** [comment]
好的

**Comment by banned-historical-archives** [comment]
https://github.com/banned-historical-archives/banned-historical-archives.github.io/discussions/365
