### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第一章后图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#2057]
```
{
    archive_id: 7,
    media: [
    {
        type: 'img',
        name: '《简明世界史（近代部分）》后图一',
        description: '审判英国国王查理一世',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》后图二',
        description: '一七七六年七月四日在费城签署美国独立宣言',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }],
}
```
![1](https://user-images.githubusercontent.com/113572850/215445522-b3e13f9b-eb15-4764-aa58-a30d24737641.png)
![2](https://user-images.githubusercontent.com/113572850/215445549-9b2d00f2-06c1-466d-b35e-016e8ae599ac.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/77/773ab58d-a1db-4181-866d-6df5a1afe098.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/d2/d2b32053-1798-4ffd-9093-bcfdbd7a8688.png"%0A]%0A```
