### ISSUE TITLE
内容问题集中反馈

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#208]
#106 
https://banned-historical-archives.github.io/articles/c1a4c8a436/

![image](https://user-images.githubusercontent.com/113572850/190944012-c3b3eab7-c710-4cee-8f27-6193b1e02785.png)

**Comment by PirateBook1** [comment]
#123 
https://banned-historical-archives.github.io/articles/e083887f1f/

**Comment by PirateBook1** [comment]
#147 
https://banned-historical-archives.github.io/articles/9bbddebe81/
https://banned-historical-archives.github.io/articles/ce457ed95c/
段落错误
这两篇来源对了，但是标题、别名和日期颠倒了

**Comment by PirateBook1** [comment]
#136 
https://banned-historical-archives.github.io/articles/f97d92e886/
段落错误

**Comment by PirateBook1** [comment]
@banned-historical-archives 希望尽快解决。另外我这边组织了几个同志帮忙录入，这些 issue 下面我都附了相应的文字版

**Comment by banned-historical-archives** [comment]
好的，可能要一个星期左右，我再思考一下怎么优化校对体验

**Comment by banned-historical-archives** [comment]
如果图像质量很差，没有OCR的必要了（不仅正确率很低，而且产生的段落问题修复难度很高），可以参考wanghongwen5.ts，直接录入篇文章。

**Comment by PirateBook1** [comment]
@banned-historical-archives 行，你可以在 wiki 里面补充手写稿参照 wanghongwen5

**Comment by PirateBook1** [comment]
日期错误，应为 1968.7.5
https://banned-historical-archives.github.io/articles/3f77aa6b2d/

**Comment by PirateBook1** [comment]
关于不完整的内容，咱们这应该怎么处理，是直接舍弃还是照常录入

**Comment by banned-historical-archives** [comment]
先忽略吧

**Comment by PirateBook1** [comment]
https://banned-historical-archives.github.io/articles/279f0fbdce/
没有校对

**Comment by PirateBook1** [comment]
https://banned-historical-archives.github.io/articles/2f4db48261/
没有校对

**Comment by PirateBook1** [comment]
https://banned-historical-archives.github.io/articles/645614c10a/
没有校对
张春桥同志重要报告

**Comment by PirateBook1** [comment]
https://banned-historical-archives.github.io/articles/645614c10a/
没有校对
张春桥同志在上海市革命委员会报告会上的讲话

**Comment by PirateBook1** [comment]
https://banned-historical-archives.github.io/articles/4d232c4587/
没有校对
张春桥同志十二月十日下午接见宣传系统代表讲话

**Comment by PirateBook1** [comment]
https://banned-historical-archives.github.io/articles/10181955f6/
两篇来源文字疑似重复

**Comment by PirateBook1** [comment]
@banned-historical-archives 这两篇为什么合不起来啊？标题不是都一样了吗
![image](https://user-images.githubusercontent.com/113572850/193395315-1a9e846a-781b-4f52-ae5e-7a333c4ac4ee.png)

**Comment by banned-historical-archives** [comment]
@PirateBook1 作者不一样
```
export function get_article_id(r: ParserResult) {
  return hash_str_arr([
    r.title,
    JSON.stringify(
      r.dates.sort((a, b) =>
        `${a.year || '0000'}-${ensure_two_digits(a.month)}-${ensure_two_digits(
          a.day,
        )}` >
        `${b.year || '0000'}-${ensure_two_digits(b.month)}-${ensure_two_digits(
          b.day,
        )}`
          ? 1
          : -1,
      ),
    ),
    JSON.stringify(r.is_range_date),
    JSON.stringify(r.authors.sort((a, b) => (a > b ? 1 : -1))),
    JSON.stringify(r.file_id || ''),
  ]);
}
```

**Comment by PirateBook1** [comment]
@banned-historical-archives 那么应该怎么改把这两篇合起来

**Comment by banned-historical-archives** [comment]
上面一篇的作者改成 authors: ['江青', '康生']

**Comment by PirateBook1** [comment]
作者改成江青和康生不太好吧，我们以文稿为准的原则，这篇文稿就是这些人讲了话

**Comment by banned-historical-archives** [comment]
那就要改下面的

**Comment by banned-historical-archives** [comment]
https://github.com/banned-historical-archives/banned-historical-archives.github.io/discussions/365

**Comment by PirateBook1** [comment]
等上面已经列出的问题解决完再关闭这个 issue
