### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第二章后图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#2081]
```
{
    archive_id: 7,
    media: [
    {
        type: 'img',
        name: '《简明世界史（近代部分）》后图三',
        description: '攻占巴斯底狱',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》后图四',
        description: '处决路易十六',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》后图五',
        description: '拿破仑的雾月十八日政变',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }],
}
```
![3](https://user-images.githubusercontent.com/113572850/216091725-48d6adb1-4dbe-426a-bde9-548348ca503c.png)
![4](https://user-images.githubusercontent.com/113572850/216091752-bf01460c-c0d3-4044-9e9b-c9293df6c7b8.png)
![5](https://user-images.githubusercontent.com/113572850/216091762-7d8eec5b-a6b3-4413-9230-b4a943c17603.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/e5/e5cb1b30-973d-4e34-9dbb-20463453364c.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/7d/7dd3ce92-638a-4315-a46d-4408ce61e295.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/d4/d4f46f8a-f563-440f-b417-e8539d50d32e.png"%0A]%0A```
