### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第三章插图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#2135]
```
{
    archive_id: 7,
    media: [
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十三',
        description: '杜桑·卢维杜尔',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十四',
        description: '西蒙·波利瓦尔',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十五',
        description: '一八一七年圣马丁率军越过安第斯山进入智利',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }
    ],
}
```
![1](https://user-images.githubusercontent.com/113572850/216777544-2f970580-e57e-4263-831e-6e9e18799f0a.png)
![2](https://user-images.githubusercontent.com/113572850/216777556-13d2d1e3-e394-4922-a6bd-530be278628c.png)
![3](https://user-images.githubusercontent.com/113572850/216777563-e00d5a80-80c6-47c0-ad45-91984ff1e07c.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/3a/3ac01f00-b037-40f9-8ba7-d663b0c01fc6.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/f3/f32b51fb-063f-4cf6-ba55-c3dc24b6f7ae.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/40/4098dd45-8b17-499a-9939-e9254344ee5e.png"%0A]%0A```
