### ISSUE TITLE
远期工作展望

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#214]
https://github.com/mlmlearner/mlmlearner

**Comment by banned-historical-archives** [comment]
我打算先整理核心人物的讲话。目前在录毛全集。

**Comment by PirateBook1** [comment]
我们目前在录那些棘手的手写稿

**Comment by PirateBook1** [comment]
你们懂得写代码的同志多编写书籍的解析器，而且应该优先解析那些质量好的。手写稿拍照稿这类需要大量人力的不必费很多心思

**Comment by banned-historical-archives** [comment]
对的

**Comment by PirateBook1** [comment]
列宁选集
https://libgen.unblockit.cat/search.php?req=%E5%88%97%E5%AE%81%E9%80%89%E9%9B%86
马克思恩格斯选集
https://libgen.unblockit.cat/search.php?req=%E9%A9%AC%E5%85%8B%E6%80%9D%E6%81%A9%E6%A0%BC%E6%96%AF%E9%80%89%E9%9B%86

可以录里面文字版的

**Comment by PirateBook1** [comment]
请问这种情况怎么办，有办法合起来吗
![image](https://user-images.githubusercontent.com/113572850/191667784-2d3fe548-3058-434d-b1ca-92a2791dcca6.png)

**Comment by banned-historical-archives** [comment]
统一一个标题就可以合并，比如统一采用上面的标题，
修改万岁这篇文章解析器，把title换成文库的标题，原标题放进alias里面

**Comment by PirateBook1** [comment]
哇哦，目前已经有同志已经拿到文化大革命文库第三版的资源了吗。如果真实现了那真是一件大好事

**Comment by banned-historical-archives** [comment]
没有拿到

**Comment by PirateBook1** [comment]
这种 .pdf 里面单篇文章的 parser 如果要改的话怎么改？在这里面粗暴加 if 判断 title 另外赋值么，我拿上面的万岁本举例

![image](https://user-images.githubusercontent.com/113572850/191699093-9373a1e8-70b0-4052-9833-dbb0a79fe3fe.png)

**Comment by banned-historical-archives** [comment]
恩，这种情况就粗暴
