### ISSUE TITLE
毛泽东全集录入

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#218]
分三步走：

1. 初步录入
2. 校对标题
3. 校对段落

## 初步录入进度：

- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10
- [ ] 11
- [ ] 12
- [ ] 13
- [ ] 14
- [ ] 15
- [ ] 16
- [ ] 17
- [ ] 18
- [ ] 19
- [ ] 20
- [ ] 21
- [ ] 22
- [ ] 23
- [ ] 24
- [ ] 25
- [ ] 26
- [x] 27
- [x] 28
- [x] 29
- [x] 30
- [x] 31
- [x] 32
- [x] 33
- [x] 34
- [x] 35
- [x] 36
- [x] 37
- [x] 38
- [x] 39
- [x] 40
- [x] 41
- [x] 42
- [x] 43
- [x] 44
- [x] 45
- [x] 46
- [x] 47
- [x] 48
- [x] 49
- [x] 50
- [x] 51
- [x] 52

**Comment by PirateBook1** [comment]
这个毛全集是文字版吗，需要校对吗

**Comment by banned-historical-archives** [comment]
ocr版，到时再校对

**Comment by banned-historical-archives** [comment]
@PirateBook1 pdf  自带的文本准确率很低，我重新跑了一遍OCR再录入的

**Comment by PirateBook1** [comment]
只能说优先弄自带文字的吧，实在是没有人手校对了……尤其是全集这种大部头……

**Comment by banned-historical-archives** [comment]
毛全集内容很丰富，也不急着校对，先录进来方便查阅

**Comment by banned-historical-archives** [comment]
@PirateBook1 你把优先级高的列出来吧

**Comment by PirateBook1** [comment]
你先说一说你计划的录入优先级，我根据你说的找材料

**Comment by banned-historical-archives** [comment]
@PirateBook1 
1.毛
2.F4 （如果是稀缺材料/搜索引擎搜不到的内容，优先级最高）

**Comment by PirateBook1** [comment]
这些你需要吗
![image](https://user-images.githubusercontent.com/113572850/191923033-15211232-6bdc-4f55-902b-79c44b103f03.png)

**Comment by banned-historical-archives** [comment]
chm很多是从pdf中ocr并校验（或者没有）来的

1.无论是否校验过，校验的过程是缺失的，这些chm就变成了无法溯源的二手信息。我希望从一个可信的数据源获取信息。
2.格式不规范，更难解析，没法区分段落/子标题，另外段落如果被分页切断需要很多信息把段落恢复。

这些chm可能用于OCR的补充校验比较合适

**Comment by PirateBook1** [comment]
那也是没办法的事，毛的著作情况好一些，四人的流传资料要么是这种老左当年弄的 .chm，要么是那种拍照稿

**Comment by banned-historical-archives** [comment]
数量太大了，1-26优先级放低，其他已经完成录入，标题初步校对（正文中的标题还没有校对），段落情况太复杂暂时不校对，尤其是批注类型的。

**Comment by PirateBook1** [comment]
毛全集的 .pdf 不打算直接放到 /public/books 里面吗

**Comment by banned-historical-archives** [comment]
@PirateBook1 毛全集占了几个G，拆出去了。以后新增的内容尽量拆除去吧。

**Comment by PirateBook1** [comment]
拆到哪？给个放的地方

**Comment by banned-historical-archives** [comment]
@PirateBook1 收到邀请了吧？拆到里面，你看情况，可以用文件夹也可以直接传

**Comment by banned-historical-archives** [comment]
@PirateBook1 也可以用mlmlearner 仓库，只是担心他们的目录结构会经常变更

**Comment by PirateBook1** [comment]
这五个库分别是放什么的

**Comment by banned-historical-archives** [comment]
@PirateBook1 随便吧

**Comment by PirateBook1** [comment]
把 book 文件夹里面的内容全部分类出来吗

**Comment by banned-historical-archives** [comment]
@PirateBook1 全部移出去需要一些时间，优先级不高，现在存在的先不动吧
