### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第四章插图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#2183]
```
{
    archive_id: 7,
    media: [
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十六',
        description: '十八世纪的日本酿酒工场',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十七',
        description: '西山起义军使用的印章和战鼓',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十八',
        description: '铁普索丹',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图十九',
        description: '英国东印度公司——掠夺亚洲人民的吸血鬼',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十',
        description: '万恶的奴隶贸易',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十一',
        description: '奴隶船的平面图',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十二',
        description: '班图人民抗击西方殖民者',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    },
    {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十三',
        description: '穆罕默德·阿里',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }
    ],
}
```
![1](https://user-images.githubusercontent.com/113572850/217449445-d2da3c8d-9faf-41de-8070-ac22929344bf.png)
![2](https://user-images.githubusercontent.com/113572850/217449454-b8647065-a5bd-4dcb-a8a0-6c09f5348f87.png)
![3](https://user-images.githubusercontent.com/113572850/217449461-103d7947-96a2-465e-8540-b09e4a7d8ea0.png)
![4](https://user-images.githubusercontent.com/113572850/217449467-102134b1-2641-4d2e-9411-9c5e6f0a23af.png)
![5](https://user-images.githubusercontent.com/113572850/217449471-81227e37-ea08-4be5-a4e6-f25a421ca5d2.png)
![6](https://user-images.githubusercontent.com/113572850/217449484-d7ad29b0-de84-4747-882e-f4e4b46da59e.png)
![7](https://user-images.githubusercontent.com/113572850/217449490-8cacca27-4e0d-4ce7-92ae-5f108573c88f.png)
![8](https://user-images.githubusercontent.com/113572850/217449498-2c63feac-d891-4800-93a4-477e3268181e.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/c5/c5a5bb3a-2470-418d-806c-042928f50cb6.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/75/752059ee-3796-4da7-b2cd-2b81724031e7.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/a7/a7a1a3e4-b69f-45cf-8c87-067d422c5c6d.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/9e/9e6895e9-ff7a-4821-875e-70af39b1f715.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/69/6954507d-58cb-4b60-874d-6f9fffb2c3c8.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/37/374c944a-81a7-4c7b-abda-d41efabedb6a.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/29/29a6b196-38d1-4e1f-9538-54bcb2201455.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/22/224d4d43-1942-40ab-991c-27e6bcef5133.png"%0A]%0A```
