### ISSUE TITLE
段落校对工具

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#219]
方便非技术人员使用的段落校对工具

段落校对和文本校对应该互相独立（这样在交互上和代码实现上都清晰很多），我计划在点击校对模式按钮后提示用户选择校对文本或者校对段落问题。

文本校对模式仅校对段落中的错漏缺的文本以及注释索引（用半角中括号加数字表示，例如[23]）

段落校对模式可编辑段落的类型（比如子标题，普通段落，引文，等等），删除段落，在段落前/后插入段落，插入段落时需要填写段落中的内容。

值得注意的是，一般情况下文本校对和段落校对不能同时进行或者说同时提交变更，在一个变更合并主干后且部署后才能再次提交。

**Comment by banned-historical-archives** [comment]
@PirateBook1 这样可以吗？

**Comment by PirateBook1** [comment]
这个现在已经部署上了吗

**Comment by banned-historical-archives** [comment]
@PirateBook1 为啥要移动？

**Comment by PirateBook1** [comment]
许多文章把某某某组织传达、某某某组织记录、某某某组织翻印这类内容都放在正文里面了，但实际上这些信息应该放描述里面

**Comment by banned-historical-archives** [comment]
哦，这种情况不会冲突，可以同时提交文本校对和段落校对

**Comment by PirateBook1** [comment]
@banned-historical-archives 开发进度怎么样了

**Comment by banned-historical-archives** [comment]
@PirateBook1 可能这一两天吧

**Comment by banned-historical-archives** [comment]
@PirateBook1 我还是把文本校对和段落校对合并在一起了，分开校对感觉比较混乱
