### ISSUE TITLE
自动化OCR录入

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#220]
设计一个 issue 录入模板，利用github workflow自动完成文稿录入。
可能类似于
```
issue标题：[文稿录入]标题。。。
issue内容：
来源名称/书籍名称：xxx
文稿标题：xxx
作者：xxx，yyy
日期：1966.10.11-15
图片：
1.jpg
2.jpg
...
```

**Comment by banned-historical-archives** [comment]
配合段落修复工具可以实现全链路无代码

**Comment by banned-historical-archives** [comment]
暂时做图片集的吧
pdf要复杂得多，包含多个标题，如何进行切割和提取标题是个问题，这个应该没办法自动化

**Comment by banned-historical-archives** [comment]
可能还需要一个中间状态的校对工具，辅助切割pdf中的标题

**Comment by PirateBook1** [comment]
不错，现在的图片集录入过程完全可以抽象成一个重复的机械过程的，无非是不断地复制 .ts 和修改里面的信息

**Comment by banned-historical-archives** [comment]
@PirateBook1 也可以

**Comment by PirateBook1** [comment]
@banned-historical-archives 下一步的开发计划是这个吗，另外可以开始考虑把书籍纳入资料库了，收录《红旗》《学习与批判》等

**Comment by banned-historical-archives** [comment]
@PirateBook1 是的

**Comment by PirateBook1** [comment]
@banned-historical-archives 我建议正文加一个子标题功能，二级标题、三级标题、四级标题。优化读者的阅读体验。甚至在未来可以开发一个目录功能。这个功能应该可以直接搬到书籍使用。

类似这种情况：
![image](https://user-images.githubusercontent.com/113572850/193441806-575e7604-2511-4ab0-841d-0c0457394abe.png)

**Comment by banned-historical-archives** [comment]
@PirateBook1 类型选subtitle就是子标题，现在只有2级

**Comment by PirateBook1** [comment]
我想说的是给子标题加一些样式，现在只是居中我觉得不太够。还有文内目录功能

**Comment by banned-historical-archives** [comment]
@PirateBook1 已经添加多级标题，subtitle2,subtitle3,subtitle4,subtitle5。

可以

**Comment by PirateBook1** [comment]
一份文稿，需要或者不需要 OCR，单个与多个作者，四种情况都要考虑到

**Comment by banned-historical-archives** [comment]
@PirateBook1 即使不需要OCR，一般情况还是要校对段落，除非配置一大堆属性。在校对段落时顺便输入正确的文字也不会很繁琐吧？

**Comment by PirateBook1** [comment]
我的意思是说不需要 OCR 时要求贡献者直接附带正确的文稿

**Comment by PirateBook1** [comment]
@banned-historical-archives 自动化录入功能已经开发完毕了吗

**Comment by banned-historical-archives** [comment]
还有点问题

**Comment by PirateBook1** [comment]
![image](https://user-images.githubusercontent.com/113572850/194795931-e1a1cb12-c3bc-4b3e-8007-a83b77874a16.png)
还有个需求，这三处地方希望志愿者同样可以直接修改到

**Comment by banned-historical-archives** [comment]
这三处在录入的时候可以，录入以后现在只能改下面的标题

**Comment by PirateBook1** [comment]
那只好直接发现后直接更改源码了

**Comment by banned-historical-archives** [comment]
@PirateBook1 现在可以了
