### ISSUE TITLE
人民日报录入进度

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#2442]

**Comment by banned-historical-archives** [comment]
目前卡在git action7z解压编码问题，预计这两天修复

**Comment by banned-historical-archives** [comment]
> Build error occurred
[Error: ENOSPC: no space left on device, copyfile '/home/runner/work/banned-historical-archives.github.io/banned-historical-archives.github.io/.next/server/pages/articles/e379e4a08b.json' -> '/home/runner/work/banned-historical-archives.github.io/banned-historical-archives.github.io/.next/standalone/.next/server/pages/articles/e379e4a08b.json'] {
  errno: -28,
  code: 'ENOSPC',
  syscall: 'copyfile',
  path: '/home/runner/work/banned-historical-archives.github.io/banned-historical-archives.github.io/.next/server/pages/articles/e379e4a08b.json',
  dest: '/home/runner/work/banned-historical-archives.github.io/banned-historical-archives.github.io/.next/standalone/.next/server/pages/articles/e379e4a08b.json'
}

**Comment by banned-historical-archives** [comment]
磁盘空间不足，只能以后精选一些文稿录入

**Comment by banned-historical-archives** [comment]
@PirateBook1

**Comment by PirateBook1** [comment]
@banned-historical-archives 磁盘空间最大能装多少，现在用了多少

**Comment by banned-historical-archives** [comment]
不清楚 github的机器限制，46-76大概30万篇文稿，init-db两个小时跑完

**Comment by PirateBook1** [comment]
@banned-historical-archives 那人民日报不录了，等以后慢慢排查吧，日后解决。

**Comment by banned-historical-archives** [comment]
@PirateBook1 可以用关键词白名单把重要文章过滤出来

**Comment by PirateBook1** [comment]
@banned-historical-archives 文革那十年有多少篇，这十年完全收录有条件吗

**Comment by banned-historical-archives** [comment]
@PirateBook1 几万篇吧，太多了

**Comment by banned-historical-archives** [comment]
1946-2003 关键词仅过滤 ['邓小平', '张春桥', '姚文元', '江青', '王洪文', '刘少奇', '关锋', '戚本禹', '文化大革命'] 共有约8万篇文章。
如果过滤到76年10月约4万篇。
目前档案馆总共5万多篇已经比较极限了，构建时存储空间本来就不太够用。

得先解决构建存储空间占用问题。

**Comment by banned-historical-archives** [comment]
https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/3955
