### ISSUE TITLE
毛泽东全集录入进度

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#2443]
- [x] 1-26

**Comment by banned-historical-archives** [comment]
https://github.com/banned-historical-archives/banned-historical-archives8/tree/main/mao-quanji
其中4,7,9,22卷超过100m无法传到仓库

@PirateBook1 你有没有其他版本的全集？

**Comment by PirateBook1** [comment]
@banned-historical-archives 没有，只能二值化一遍文字页面以缩小文件

**Comment by PirateBook1** [comment]
你需要的话我可以帮你处理

**Comment by banned-historical-archives** [comment]
@PirateBook1 可以

**Comment by PirateBook1** [comment]
@banned-historical-archives Git LFS 你研究过吗，好像可以上传超过 100m 的文件

**Comment by banned-historical-archives** [comment]
@PirateBook1 LFS和平台捆绑太深了

**Comment by PirateBook1** [comment]
@banned-historical-archives 四本已上传，在我的 books 库里
