### ISSUE TITLE
揭发“四人帮”王洪文插手控制上影阴谋篡党夺权的罪行

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#245]
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_1](https://user-images.githubusercontent.com/113572850/193768688-e7554508-5ccb-4d23-99c1-79f561fefef5.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_2](https://user-images.githubusercontent.com/113572850/193768699-f8007704-bdc3-4f9f-b144-f5fe9e77413a.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_3](https://user-images.githubusercontent.com/113572850/193768704-f2c046f2-e56b-49dc-b3e3-2e5722ba2c2e.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_4](https://user-images.githubusercontent.com/113572850/193768707-83ed04ba-1e69-4260-bced-460b65ede0d6.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_5](https://user-images.githubusercontent.com/113572850/193768711-a35016d8-d245-4312-9ddd-34f0c09acdc0.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_6](https://user-images.githubusercontent.com/113572850/193768716-cc7d2b21-6b1a-44c3-82b5-02abf756f353.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_7](https://user-images.githubusercontent.com/113572850/193768722-3e2726b3-6b40-415a-b27a-c3ffce68ac8d.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_8](https://user-images.githubusercontent.com/113572850/193768728-6e31b7a4-e6e5-4b1c-a300-817b26455605.jpg)
![王洪文1975年8月31日审查《春苗》9月4日审查《战船台》与在9月3日电影工业会议和10月14日在上海文艺座谈会上讲话、1976年5月8日在钓鱼台与张家龙等的讲话_页面_9](https://user-images.githubusercontent.com/113572850/193768731-04d36bf4-56c9-4c70-a8d1-c8d24c0a890e.jpg)

**Comment by banned-historical-archives** [comment]
#362

**Comment by PirateBook1** [comment]
这份稿还没完，

**Comment by banned-historical-archives** [comment]
@PirateBook1 不完整？

**Comment by PirateBook1** [comment]
这份揭批查文稿里实际有四到五篇王洪文讲话

**Comment by PirateBook1** [comment]
@banned-historical-archives 《春苗》《战船台》电影工业会议这三个应该分开，而且第一、二部分里面都有《春苗》，情况比较复杂

**Comment by PirateBook1** [comment]
第一部分的“三”和“四”什么时候讲的不清楚，也需要另外开 title

**Comment by PirateBook1** [comment]
@banned-historical-archives 你先把这篇在资料库里的东西删掉再推上来吧，明天我再重新开一个 issue。这篇已经有文字稿了

**Comment by banned-historical-archives** [comment]
恩，这种是引用多个时间段部分讲话的文章，没办法拆开吧

**Comment by banned-historical-archives** [comment]
我建议留着。这篇文章就作为独立的文稿。如果有原始的讲话稿当然更好，与这篇文章也不冲突。

**Comment by PirateBook1** [comment]
> 我建议留着。这篇文章就作为独立的文稿。如果有原始的讲话稿当然更好，与这篇文章也不冲突。

留着就留着吧，不是什么很大的问题

**Comment by banned-historical-archives** [comment]
恩，有空你来帮忙处理一下仓库分类的事情吧

**Comment by PirateBook1** [comment]
怎么分类的问题目前需要讨论的不多，目前等待录入的就只有 Prolet 库的造反派文稿，这些全部扔 archive1 就好了。主要是看资料库会不会收书籍，如果打算收书籍的话才有讨论分类的必要

**Comment by banned-historical-archives** [comment]
书籍应该快了，我在做pdf的自动化录入

**Comment by PirateBook1** [comment]
@banned-historical-archives 你可以做一做这本。这个目前有文字稿
[马克思恩格斯：共产党宣言1963.pdf](https://github.com/banned-historical-archives/banned-historical-archives.github.io/files/9746944/1963.pdf)

**Comment by banned-historical-archives** [comment]
我想先把报纸，杂志录入进来
