### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第五章插图和后图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#2799]
```
{
    archive_id: 7,
    media: [{
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十四',
        description: '布朗基',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十五',
        description: '青年时代的马克思',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十六',
        description: '青年时代的恩格斯',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十七',
        description: '《共产党宣言》第一版',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》后图八',
        description: '英国伦敦的贫民窟',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》后图九',
        description: '一八三四年里昂工人起义',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》后图十',
        description: '马克思在共产主义者同盟会议上',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }],
}
```
![1](https://user-images.githubusercontent.com/113572850/226272296-f7d06ac6-9129-413e-a2e1-faba81851379.png)
![2](https://user-images.githubusercontent.com/113572850/226272302-40282679-165d-4c27-ae33-eb630cf0a894.png)
![3](https://user-images.githubusercontent.com/113572850/226272305-469f74e1-9743-44db-a4cb-cdadf18b3d80.png)
![4](https://user-images.githubusercontent.com/113572850/226272310-9273ece6-d396-4ac0-9600-f6d9f7092a85.png)
![5](https://user-images.githubusercontent.com/113572850/226272311-90ee1141-df26-47c5-a930-2f2685716a52.png)
![6](https://user-images.githubusercontent.com/113572850/226272315-83a5e89f-26fe-4307-ad87-6817e41b670f.png)
![7](https://user-images.githubusercontent.com/113572850/226272319-18cfec0c-ec4e-49e1-b4e9-242c1bd63c68.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/ee/ee77f6f7-9fc0-4c01-8bfa-aa0a7970d547.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/34/34012035-915e-4d93-b534-25b33d3ef935.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/ea/eada8981-37bd-488e-b63d-00db0d97eed6.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/23/23344f86-9139-4def-b1be-b5248227a6c9.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/fa/fa4a6c48-ea9f-4b9e-acba-a2c90f61c5ca.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/05/05e2697e-770c-4223-9221-cd0feca3aabe.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/2c/2c9eab44-2cfa-40f3-b26b-beb3538c406b.png"%0A]%0A```
