### ISSUE TITLE
[自动化多媒体录入]《简明世界史（近代部分）》第六章插图和后图

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#2816]
```
{
    archive_id: 7,
    media: [{
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十八',
        description: '革命群众焚毁国王“宝座”',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图二十九',
        description: '匈牙利起义（中立者为苏科特）',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图三十',
        description: '贝拉采斯库',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图三十一',
        description: '《新莱茵报》最后一期',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图三十二',
        description: '加里波第',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》插图三十三',
        description: '东布罗夫斯基',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》后图十一',
        description: '一八四八年柏林三月起义',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》后图十二',
        description: '一八四八年捷克布拉格人民起义',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》后图十三',
        description: '一八四八年巴黎六月起义',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }, {
        type: 'img',
        name: '《简明世界史（近代部分）》后图十四',
        description: '一八四九年恩格斯参加街垒战斗',
        source: '《简明世界史（近代部分）》',
        show_in_gallery: true,
        tags: [],
    }],
}
```
![1](https://user-images.githubusercontent.com/113572850/227129789-c5c27955-df82-4762-9ea4-cc9469e2be49.png)
![2](https://user-images.githubusercontent.com/113572850/227129801-e495bf9f-4483-4a75-acb9-84f400374d4e.png)
![3](https://user-images.githubusercontent.com/113572850/227129808-dc1a78de-ed2a-49fc-980c-c13ac9d8b05f.png)
![4](https://user-images.githubusercontent.com/113572850/227129812-daec6c3a-b255-459b-9ea3-467bbd590517.png)
![5](https://user-images.githubusercontent.com/113572850/227129816-057aeae1-c1b0-4907-87b4-7f9d2eab1414.png)
![6](https://user-images.githubusercontent.com/113572850/227129821-cef077b6-35b9-47b6-9a94-2aae23e5b9f7.png)
![7](https://user-images.githubusercontent.com/113572850/227129822-83b76ef1-5a10-4ec2-8af7-c02983763239.png)
![8](https://user-images.githubusercontent.com/113572850/227129825-b999deb8-e3df-4e33-a92b-06ffb83b7ca0.png)
![9](https://user-images.githubusercontent.com/113572850/227129835-cdf51f6a-9722-43c3-977e-eb2ac36c9f7c.png)
![10](https://user-images.githubusercontent.com/113572850/227129839-30481e21-285d-4adc-8c17-472847086f2b.png)

**Comment by banned-historical-archives** [comment]
```%0A[%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/56/56819f9f-1228-46de-a45f-2a404111feb8.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/36/362c233c-3ffa-4f80-8900-e2594ead17aa.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/31/31ff39e3-af42-47f2-b78f-c6db503abbcc.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/97/97b78fd6-9305-424f-bda9-e30d23210a86.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/f1/f1fac1d0-ab93-46cf-8934-0b1100ab22f8.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/07/07c4bf5f-f143-4097-903e-e47eb4004457.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/b4/b4324eb6-f428-467e-93f5-bc603c6cb8bf.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/9a/9a1cbfe6-7fea-487a-b82e-a2ab2451c042.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/39/396837f6-6624-419e-8849-b67dbd4fc775.png",%0A  "https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives7/main/5e/5e676653-9f74-4028-9558-11ecb7b5e1c4.png"%0A]%0A```
