### ISSUE TITLE
“邓小平在毛泽东去世后发动政变夺取政权”缺乏材料依据

### ISSUE THREAD

**Issue by yunzhijuezhong** [banned-historical-archives/banned-historical-archives.github.io#2975]
反对邓、反对后三十年的人并不少，但是你们整理的这个文库并没有材料证明你们所提出的“被封禁的资料中揭露的内容”第二大点。

四人帮是否为邓小平镇压的？1976年邓被开除一切职务，毛逝世后执掌权力的是华国锋等人物，而这些人，包括所有能找到的亲历镇压四人帮的人（连同所谓江青集团被打倒者），均没有提过“邓小平发动政变”。我找遍了你们这个文库也没发现哪里能证明邓发动政变夺取政权。

**Comment by banned-historical-archives** [comment]
> 我们当时还不知道是谁搞的这次政变，但心里都猜测可能是被打倒的邓小
> 平一伙。后来逐渐出了大量的文章，才知道是叶剑英、华国锋、李先念、汪东
> 兴等几个人密谋干的。因为政变成功了，他们都想表一表自己功劳，并不觉得
> 这是见不得阳光的事，我们才有幸看到这些情节。如果失败了，他们可能溜得
> 比兔子还快。邓小平复出后，我又见到一些文章中写道，在密谋时，邓小平化
> 了妆亲自去叶剑英家商议，政变成功后叶剑英又第一时间给邓小平做了汇报，
> “邓小平高兴极了”。当时邓已被解除党内外一切职务，叶凭什么要去向他汇
> 报，这还不说明问题吗？背后还是邓小平在出谋划策。还是邓小平女儿有点头
> 脑，估计认识到这毕竟是见不得阳光的事，赶紧写文章说：爸爸那时正“软禁”
> 在家，不可能去叶剑英家。叶剑英秘书“拎不清“，又写文章说他亲眼看到邓
> 小平下午几点几分，手里拿着一份《人民日报》去叶家的。这些都是上世纪八
> 九十年代看到的。

黄金海回忆录

**Comment by banned-historical-archives** [comment]
或许不是很严谨，晚点我再搜一下其他资料

**Comment by yunzhijuezhong** [comment]
1，原造反派黄金海所谓的“一些文章”，恐怕是一些谣言而已。毛逝世之后“邓化妆暗访”这么重大的历史细节，即使是坚持毛主义的学者都没有一个人考据过，即使是反对后三十年的媒体（诸如乌有之乡）也没有任何人士讨论，因为这根本不是一个严肃的历史论题。
2，要注意汪东兴这个人，他即使到1976年12月四人帮倒台后，都还是坚持批邓的，“ 现在邓小平问题也没有划为敌我矛盾。谁划了？他还是‘以观后效’” “邓小平的那两下子，不是（在 1975年）试过了吗？就是不行嘛！”。这些发言可以看出直接指挥8341部队的汪东兴并没有瞧得上邓，那就更不可能在说这些话的两个月前接受邓的领导和安排，去调动8341了。
3，“谋划粉碎四人帮”在官方叙事中并不是见不得光的事，华、叶、汪也没因为深度参与此事在社会或党政军内部留下负面影响，反而成了政治生命中大快人心的一笔。黄金海对邓榕写文澄清的动机揣测显然站不住脚。

**Comment by banned-historical-archives** [comment]
化妆看起来是有点扯，我只是关注后面向邓汇报那句，如果这是官方媒体或者内部泄露的文件披露的，邓榕和秘书随后赶紧写文章重置历史那整个故事就比较可信了。
暂未找到向邓汇报的信息来源。因为邓处在观察期，如果与叶有联系当然是不光彩的。

>  叶帅说，小平是要出来工作，不过要晚一点。车子转弯转得太急要翻车的。小平这个事是毛主席提的，政治局通过留党察看、以观后效的，现在一下子马上出来不行，要一个过程。不然真成了宫廷政变。



关于汪东兴你说的很对，我比较相信这个说法。现在去修改一下README。
