### ISSUE TITLE
[OCR patch]千万不要忘记阶级斗争[红旗一九六六年第七期][0e808e1633][33d26a96-67db-4a35-a4ce-d02beb985e58]

### ISSUE THREAD

**Issue by MinecraftTAO** [banned-historical-archives/banned-historical-archives.github.io#3104]
{OCR补丁}
{"articleId":"0e808e1633","publicationId":"33d26a96-67db-4a35-a4ce-d02beb985e58","patch":{"version":2,"parts":{"0":{"diff":"=9\t-1\t+%E4%BA%89"},"1":{"diff":"=7\t+%E8%AE%BA"},"2":{"diff":"=22\t-1\t+%E4%B9%89\t=409"},"3":{"diff":"=437\t+%E5%9C%BA%E6%96%97%E4%BA%89%EF%BC%9A%E4%B8%80%E6%AC%A1%E6%96%97%E4%BA%89%E6%AF%94%E4%B8%80%E6%AC%A1%E6%96%97%E4%BA%89%E6%9B%B4%E6%B7%B1%E5%85%A5%E3%80%82%E6%90%9E%E6%8E%89%E8%BF%99%E6%9D%A1%E9%BB%91%E7%BA%BF%E4%B9%8B%E5%90%8E%EF%BC%8C%E8%BF%98%E4%BC%9A%E6%9C%89%E5%B0%86%E6%9D%A5%E7%9A%84%E9%BB%91%E7%BA%BF%EF%BC%8C%E8%BF%98%E5%BE%97%E5%86%8D%E6%96%97%E4%BA%89%E3%80%82%E8%BF%99%E5%B0%B1%E8%AF%B4%E6%98%8E%EF%BC%8C%E9%98%B6%E7%BA%A7%E6%96%97%E4%BA%89%E6%98%AF%E4%B8%8D%E4%BE%9D%E4%BA%BA%E4%BB%AC%E7%9A%84%E6%84%8F%E5%BF%97%E4%B8%BA%E8%BD%AC%E7%A7%BB%E7%9A%84%EF%BC%8C%E6%98%AF%E4%B8%8D%E5%8F%AF%E9%81%BF%E5%85%8D%E7%9A%84%E3%80%82%E5%8F%8D%E5%85%9A%E5%8F%8D%E7%A4%BE%E4%BC%9A%E4%B8%BB%E6%94%AF%E5%88%86%E5%AD%90%E7%9A%84%E8%B5%84%E4%BA%A7%E9%98%B6%E7%BA%A7%E6%9C%AC%E6%80%A7%EF%BC%8C%E6%80%BB%E6%98%AF%E8%A6%81%E6%83%B3%E5%B0%BD%E5%90%84%E7%A7%8D%E5%8A%9E%E6%B3%95%EF%BC%8C%E9%A1%BD%E5%BC%BA%E5%9C%B0%E8%A1%A8%E7%8E%B0%E5%87%BA%E6%9D%A5%E3%80%82%E8%A6%81%E4%BB%96%E4%BB%AC%E4%B8%8D%E5%8F%8D%E6%98%A0%EF%BC%8C%E4%B8%8D%E8%A1%A8%E7%8E%B0%E6%98%AF%E4%B8%8D%E5%8F%AF%E8%83%BD%E7%9A%84%E3%80%82%E8%BF%99%E4%BA%9B%E4%BA%BA%E5%8F%A3%E4%B9%B0%E4%B8%8A%E6%8B%A5%E6%8A%A4%E7%A4%BE%E4%BC%9A%E4%B8%BB%E4%B9%89%EF%BC%8C%E5%AE%9E%E9%99%85%E4%B8%8A%E8%BF%B7%E6%81%8B%E8%B5%84%E6%9C%AC%E4%B8%BB%E4%B9%89%EF%BC%8C%E6%AD%BB%E6%8A%B1%E7%9D%80%E8%B5%84%E4%BA%A7%E9%98%B6%E7%BA%A7%E7%9A%84%E6%88%B7%E4%B8%8D%E6%94%BE%E3%80%82%E4%BB%96%E4%BB%AC%E5%AF%B9%E6%97%A0%E4%BA%A7%E9%98%B6%E7%BA%A7%E4%B8%93%E6%94%BF%E6%80%80%E7%9D%80%E6%95%8C%E5%AF%B9%E6%83%85%E7%BB%AA%EF%BC%8C%E5%86%85%E5%BF%83%E6%85%88%E7%9D%80%E4%B8%80%E8%82%A1%E5%AF%B9%E5%85%9A%E5%AF%B9%E7%A4%BE%E4%BC%9A%E4%B8%BB%E4%B9%89%E7%9A%84%E6%81%A8%E5%92%8C%E5%A1%9E%E6%B0%94%EF%BC%8C%E4%B8%80%E6%9C%89%E9%80%82%E5%BD%93%E7%9A%84%E6%B0%94%E5%80%99%EF%BC%8C%E5%B0%B1%E5%86%92%E5%87%BA%E6%9D%A5%EF%BC%9B%E4%B8%80%E6%9C%89%E9%A3%8E%E5%90%B9%E8%8D%89%E5%8A%A8%EF%BC%8C%E5%B0%B1%E7%BA%B7%E7%BA%B7%E5%87%BA%E7%AC%BC%E3%80%82%E4%BB%96%E4%BB%AC%E5%9C%A8%E4%B8%80%E5%86%8D%E5%9C%B0%E9%80%A0%E5%88%B0%E5%B9%BF%E5%A4%A7%E7%BE%A4%E4%BC%97%E7%9A%84%E6%8F%AD%E9%9C%B2%E3%80%81%E6%89%B9%E5%88%A4%E3%80%81%E6%89%93%E5%87%BB%E4%BB%A5%E5%90%8E%EF%BC%8C%E5%B0%B1%E9%87%87%E5%8F%96%E4%BA%86%E6%9B%B4%E8%94%BD%E3%80%81%E8%8E%B7%E6%BB%91%E3%80%81%E8%BF%81%E5%9B%9E%E3%80%81%E6%9B%B2%E6%8A%98%E7%9A%84%E6%89%8B%E6%B3%95%EF%BC%8C%E7%BB%A7%E7%BB%AD%E5%90%91%E5%85%9A%E5%90%91%E7%A4%BE%E4%BC%9A%E4%B8%BB%E4%B9%89%E8%BF%B9%E6%94%BB%E3%80%82"},"4":{"delete":true}},"comments":{},"description":""}}
请复制以上代码在对比选项中粘贴进行预览：https://banned-historical-archives.github.io/articles/0e808e1633

**Comment by banned-historical-archives** [comment]
https://github.com/banned-historical-archives/banned-historical-archives.github.io/actions/runs/5766937122?notification_referrer_id=NT_kwDOBo4MkbQ3Mjg3OTcwMjA3OjEwOTk3MjYyNQ&notifications_query=is%3Aunread

现在构建的机器限制了磁盘空间，我正想办法解决
