### ISSUE TITLE
毛泽东思想万岁 扫描版 录入进度

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#374]
目前采用的是网友制作的（OCR+部分校对）可检索PDF版本，可能和马克思主义文库是同一个版本

网络上还有一个含有原始图片的版本，为了尽可能溯源，有时间将会重新OCR并录入。

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5

**Comment by PirateBook1** [comment]
可以删掉旧的换新的

**Comment by PirateBook1** [comment]
@banned-historical-archives 原始图片版本的文件发一下吧

**Comment by banned-historical-archives** [comment]
@PirateBook1 毛泽东博览里面有

**Comment by banned-historical-archives** [comment]
发现可检索PDF版本有许多遗漏的文稿

**Comment by PirateBook1** [comment]
@banned-historical-archives 我们工作全面转移到录入新得到的文库第三版资料吧
