### ISSUE TITLE
[自动化多媒体录入]张春桥在法庭上

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#3868]
```
{
    archive_id: 7,
    media: [{
        type: 'img',
        name: '张春桥在法庭上1',
        description: '张春桥在法庭上',
        source: '文革网',
        show_in_gallery: true,
        tags: [],
        year: 1980, // 可选
        month: 9, // 可选
        day: 29, // 可选
    }, {
        type: 'img',
        name: '张春桥在法庭上2',
        description: '张春桥在法庭上',
        source: '文革网',
        show_in_gallery: true,
        tags: [],
        year: 1980, // 可选
        month: 9, // 可选
        day: 29, // 可选
    }, {
        type: 'img',
        name: '张春桥在法庭上3',
        description: '张春桥在法庭上',
        source: '文革网',
        show_in_gallery: true,
        tags: [],
        year: 1980, // 可选
        month: 9, // 可选
        day: 29, // 可选
    }, {
        type: 'img',
        name: '张春桥在法庭上4',
        description: '张春桥在法庭上',
        source: '文革网',
        show_in_gallery: true,
        tags: [],
        year: 1980, // 可选
        month: 9, // 可选
        day: 29, // 可选
    }, {
        type: 'img',
        name: '张春桥在法庭上5',
        description: '张春桥在法庭上',
        source: '文革网',
        show_in_gallery: true,
        tags: [],
        year: 1980, // 可选
        month: 9, // 可选
        day: 29, // 可选
    }, {
        type: 'img',
        name: '张春桥在法庭上6',
        description: '张春桥在法庭上',
        source: '文革网',
        show_in_gallery: true,
        tags: [],
        year: 1980, // 可选
        month: 9, // 可选
        day: 29, // 可选
    }, {
        type: 'img',
        name: '张春桥在法庭上7',
        description: '张春桥在法庭上',
        source: '文革网',
        show_in_gallery: true,
        tags: [],
        year: 1980, // 可选
        month: 9, // 可选
        day: 29, // 可选
    }],
}
```
![张春桥在法庭 (1)](https://github.com/banned-historical-archives/banned-historical-archives.github.io/assets/113572850/c442cfd7-0e55-4980-a03b-4598a0828851)
![张春桥在法庭 (2)](https://github.com/banned-historical-archives/banned-historical-archives.github.io/assets/113572850/a368bb3b-eb1e-48c5-86e1-42b081dfb367)
![张春桥在法庭 (3)](https://github.com/banned-historical-archives/banned-historical-archives.github.io/assets/113572850/e34cfb91-3340-4d22-86bc-bf0650744285)
![张春桥在法庭 (4)](https://github.com/banned-historical-archives/banned-historical-archives.github.io/assets/113572850/ee1b7b18-98ce-4009-9277-c17255b25d73)
![张春桥在法庭 (5)](https://github.com/banned-historical-archives/banned-historical-archives.github.io/assets/113572850/efbcb919-3ed5-4984-8008-8163a7afb121)
![张春桥在法庭 (6)](https://github.com/banned-historical-archives/banned-historical-archives.github.io/assets/113572850/9cf5f364-624a-4012-a4d1-854e4aeebac0)
![张春桥在法庭 (7)](https://github.com/banned-historical-archives/banned-historical-archives.github.io/assets/113572850/edd32f01-07dd-4a68-8e98-93995c01e6e7)

**Comment by banned-historical-archives** [comment]
已修复，参考
https://github.com/banned-historical-archives/banned-historical-archives.github.io/issues/3933

一次只能录一张图，批量操作可以参考文稿，直接写入子仓库的config
