### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by ahzvenol** [banned-historical-archives/banned-historical-archives.github.io#40]
点击对比-对比原始文件（pdf），等待pdf加载完成，切换到“No PDF file specified.”的另一页，再切回来就会挂掉
测试平台chrome，edge
测试链接：
https://banned-historical-archives.github.io/articles/c0454323f8/
https://banned-historical-archives.github.io/articles/16319adfdc/

**Comment by banned-historical-archives** [comment]
感谢反馈，已经修复，等待部署
