### ISSUE TITLE
毛远新破坏民兵建设的部分罪行材料 一九七六年十二月 资料贡献

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#42]
![毛远新关于民兵问题的部分讲话01](https://user-images.githubusercontent.com/110591488/182824002-02ccc959-db51-4e36-b3c1-267a371ab08a.jpg)
![毛远新关于民兵问题的部分讲话02](https://user-images.githubusercontent.com/110591488/182823727-b41bae94-2b09-4973-abbd-24b8d01a0c70.jpg)
![毛远新关于民兵问题的部分讲话03](https://user-images.githubusercontent.com/110591488/182823739-c2eabcc3-953a-47d3-83e7-585ebc511712.jpg)
![毛远新关于民兵问题的部分讲话04](https://user-images.githubusercontent.com/110591488/182823754-2ad9dfba-70e0-4b5e-86ee-35d473f9e1de.jpg)
![毛远新关于民兵问题的部分讲话05](https://user-images.githubusercontent.com/110591488/182823777-06ae869d-40ff-42b4-a867-8c63de20f73d.jpg)
![毛远新关于民兵问题的部分讲话06](https://user-images.githubusercontent.com/110591488/182823791-c7c53440-5c36-44cc-9091-0e940564c4ae.jpg)
![毛远新关于民兵问题的部分讲话07](https://user-images.githubusercontent.com/110591488/182823806-9d72b7fc-7650-4ffe-bdfe-c7f269ee8cb8.jpg)
![毛远新关于民兵问题的部分讲话08](https://user-images.githubusercontent.com/110591488/182823819-bd36c14f-bd2f-458b-a2e1-d0b696a8a090.jpg)
![毛远新关于民兵问题的部分讲话09](https://user-images.githubusercontent.com/110591488/182823841-0b8bb991-4790-44ee-89a3-b8adc1b3f408.jpg)
![毛远新关于民兵问题的部分讲话10](https://user-images.githubusercontent.com/110591488/182823855-9675d2b0-9de9-49a4-be5a-8252721e0ec3.jpg)
![毛远新关于民兵问题的部分讲话11](https://user-images.githubusercontent.com/110591488/182823870-9f77c046-6d4e-4ecb-acbb-c8253fb67df8.jpg)
![毛远新关于民兵问题的部分讲话12](https://user-images.githubusercontent.com/110591488/182823881-f5fa406c-8ac6-4c63-972b-2778b5688b6d.jpg)
![毛远新关于民兵问题的部分讲话13](https://user-images.githubusercontent.com/110591488/182823927-03d0642b-a469-4a80-b1ad-81ae8f45c48a.jpg)
![毛远新关于民兵问题的部分讲话14](https://user-images.githubusercontent.com/110591488/182823949-aa462a17-e4c0-4e5c-a9d5-487dbad7316c.jpg)
![毛远新关于民兵问题的部分讲话15](https://user-images.githubusercontent.com/110591488/182823969-561c9912-b529-49fe-9606-93387e8e0279.jpg)
![毛远新关于民兵问题的部分讲话16](https://user-images.githubusercontent.com/110591488/182823995-0c332e0a-38e1-40d4-b2b7-654ae366bbfb.jpg)

**Comment by banned-historical-archives** [comment]
收到，晚一点测试一下

**Comment by banned-historical-archives** [comment]
![2022-08-04T22:59:29+08:00](https://user-images.githubusercontent.com/109972625/182880423-588150be-c207-4184-8054-9afe573e059a.png)
效果一般，背景不太干净，除此之外，每张图片的正文边距都不同，有些还有扭曲，这类资料我需要做很多预处理工作把排版问题解决了，才能导入进去让你们校对错字。
这是你自己拍的吗？可以用扫描仪吗？

**Comment by 106coup** [comment]
![毛远新关于民兵问题的部分讲话01](https://user-images.githubusercontent.com/110591488/182999359-68c412c8-12a8-4a3f-a44d-655c9bf90b34.png)
![毛远新关于民兵问题的部分讲话02](https://user-images.githubusercontent.com/110591488/182999362-b369f0d3-9411-4cb8-ac55-7e99a08b7d46.png)
![毛远新关于民兵问题的部分讲话03](https://user-images.githubusercontent.com/110591488/182999365-b953140a-5c4a-4064-ba54-9d655acd10a0.png)
![毛远新关于民兵问题的部分讲话04](https://user-images.githubusercontent.com/110591488/182999366-f023c084-611b-4c86-856f-6cbac7fae964.png)
![毛远新关于民兵问题的部分讲话05](https://user-images.githubusercontent.com/110591488/182999368-42898c14-2647-4a1c-9da6-b77185ef7175.png)
![毛远新关于民兵问题的部分讲话06](https://user-images.githubusercontent.com/110591488/182999371-af5abb24-6553-4a39-816c-76619126b3f6.png)
![毛远新关于民兵问题的部分讲话07](https://user-images.githubusercontent.com/110591488/182999373-e78b6be6-38b5-4103-8997-7a32139d4552.png)
![毛远新关于民兵问题的部分讲话08](https://user-images.githubusercontent.com/110591488/182999375-04a6bdfb-ea47-424f-903f-5347ed33cd5f.png)
![毛远新关于民兵问题的部分讲话09](https://user-images.githubusercontent.com/110591488/182999376-2f0c41ce-fae9-4e21-a6d7-27a4a4d22b01.png)
![毛远新关于民兵问题的部分讲话10](https://user-images.githubusercontent.com/110591488/182999380-8424ead8-828a-4810-9cf4-204c719de381.png)
![毛远新关于民兵问题的部分讲话11](https://user-images.githubusercontent.com/110591488/182999382-afef0688-152f-40cd-9bce-33262a772cbb.png)
![毛远新关于民兵问题的部分讲话12](https://user-images.githubusercontent.com/110591488/182999384-1677b2bb-4a12-48f2-a1fc-ac4f84d36cda.png)
![毛远新关于民兵问题的部分讲话13](https://user-images.githubusercontent.com/110591488/182999387-b9f2ca71-316c-4a6e-b6c3-3d5500ffdf01.png)
![毛远新关于民兵问题的部分讲话14](https://user-images.githubusercontent.com/110591488/182999389-c73c6e99-8fbd-4cf8-a63d-37bf4847d394.png)
![毛远新关于民兵问题的部分讲话15](https://user-images.githubusercontent.com/110591488/182999391-efdac4e8-1e43-4130-805f-ce188b0900f6.png)
![毛远新关于民兵问题的部分讲话16](https://user-images.githubusercontent.com/110591488/182999353-b8ef708d-06c3-4235-8274-a50103a06d60.png)

**Comment by banned-historical-archives** [comment]
二值化可能可以解决一些背景不干净的问题，但会让文字损失一些细节，降低识别成功率。
也不能提高扭曲文字的识别率，拍摄时纸张卷曲产生的扭曲，不是透视变形。如果只是透视变形（纸张放平，任意角度拍摄），识别效果还是不错的。

**Comment by banned-historical-archives** [comment]
![2022-08-05T12:46:40+08:00](https://user-images.githubusercontent.com/109972625/183003491-4ebbd6be-7ee3-45bf-afd9-b6900182f930.png)
![2022-08-05T12:48:05+08:00](https://user-images.githubusercontent.com/109972625/183003639-75b0cdd1-e7b5-4d6a-9099-7ab371b7b5c5.png)
上图的第二页第一行“国家”识别错误。下图我做了扭曲纠正，否则左侧上部分也是识别不了。
