### ISSUE TITLE
上海工人革命造反总司令部斗争纪要 《工人造反报》编辑部 《一月风暴》编辑部 一月风暴丛书

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#45]
![1](https://user-images.githubusercontent.com/110591488/183083348-452227c8-ae66-465a-b0aa-a00bcf74c4f2.jpg)
![2](https://user-images.githubusercontent.com/110591488/183083378-abe210d9-5de2-4be9-80fb-ed3bf1f68ab5.jpg)
![3](https://user-images.githubusercontent.com/110591488/183083395-093e19e0-6585-4ac7-ba56-c27249ab5c5c.jpg)
![4](https://user-images.githubusercontent.com/110591488/183083411-ccfc09eb-f185-4673-a405-56dd3a3155d8.jpg)
![5](https://user-images.githubusercontent.com/110591488/183083436-b534f63f-f1c7-4969-83d6-a822ee7862ba.jpg)
![6](https://user-images.githubusercontent.com/110591488/183083453-fae2fc77-aa18-4b26-b9ea-227d10010e16.jpg)
![7](https://user-images.githubusercontent.com/110591488/183083478-5c3f378f-1482-4959-8ffd-6f0af96d5a6f.png)
![8](https://user-images.githubusercontent.com/110591488/183083482-aff500bb-b480-40ea-95d1-d19a5bd32d1c.png)
![9](https://user-images.githubusercontent.com/110591488/183083493-661b1017-bb9c-4e85-bf53-31a4c0f67358.png)
![10](https://user-images.githubusercontent.com/110591488/183083555-fcf9f093-3911-4e74-867d-bc338c11707c.png)
![11](https://user-images.githubusercontent.com/110591488/183083577-b01a1662-58a8-4951-a67f-e1204ece668e.png)
![12](https://user-images.githubusercontent.com/110591488/183083586-336bc937-8364-4f4a-8608-765d2647f6bc.png)
![13](https://user-images.githubusercontent.com/110591488/183083601-c9f91126-9dd4-4181-a58a-344cb3ce422c.png)
![14](https://user-images.githubusercontent.com/110591488/183083616-4090dfe5-0067-433d-b5b2-a1621b4117d5.png)
![15](https://user-images.githubusercontent.com/110591488/183083621-4c0de8a0-fb5b-4c07-ad86-815917d1ea2e.png)
![16](https://user-images.githubusercontent.com/110591488/183083636-1f1548af-bc04-48a2-bb10-2fbed9fb4550.png)
![17](https://user-images.githubusercontent.com/110591488/183083644-05af52a7-53d7-44c0-ac7b-f25d7e33d863.png)
![18](https://user-images.githubusercontent.com/110591488/183083650-f51685fc-25b0-485b-ba38-f41f965cd78f.png)
![19](https://user-images.githubusercontent.com/110591488/183083655-a868c0b8-e7c1-45bf-b6e4-59df696e8932.png)
![20](https://user-images.githubusercontent.com/110591488/183083662-0c94ac86-8485-4f9d-944c-99a9e144b96b.png)
![21](https://user-images.githubusercontent.com/110591488/183083673-229bbec0-2749-4648-8eb9-ec2e786696d0.png)
![22](https://user-images.githubusercontent.com/110591488/183083689-f7b88aef-46ad-493e-a60d-ad47e0db509f.png)
![23](https://user-images.githubusercontent.com/110591488/183083698-a8acfcfb-b524-406d-a732-d0382421c57a.png)
![24](https://user-images.githubusercontent.com/110591488/183083703-b0649431-0936-41eb-a238-28557526a911.png)
![25](https://user-images.githubusercontent.com/110591488/183083707-0ebdaa87-7284-40c0-8f2d-570aa8d2bc7c.png)
![26](https://user-images.githubusercontent.com/110591488/183083713-21d4bddb-9898-43ef-a101-7308a6ff378d.png)
![27](https://user-images.githubusercontent.com/110591488/183083716-985f6349-4425-43e9-a1ea-85e66bf2feb5.png)
![28](https://user-images.githubusercontent.com/110591488/183083722-af005221-c720-4188-8d3a-5ac00926e37a.png)
![29](https://user-images.githubusercontent.com/110591488/183083729-a5340f51-5c64-4a0d-8d2c-58a2b34b41a1.png)
![30](https://user-images.githubusercontent.com/110591488/183083732-a63222ec-fd90-42b5-82c4-677a746c6e3b.png)
![31](https://user-images.githubusercontent.com/110591488/183083737-99bda1d7-a99e-439d-b072-08c7ad1c9020.png)
![32](https://user-images.githubusercontent.com/110591488/183083740-9a7c7888-9f04-413a-997a-754c2b8fdf5a.png)
![33](https://user-images.githubusercontent.com/110591488/183083744-35dfcaab-27e3-4237-ad18-2cbbae598b03.png)
![34](https://user-images.githubusercontent.com/110591488/183083264-a7ea2bb5-b8c9-4534-91f5-3da5b25c44ff.png)
![35](https://user-images.githubusercontent.com/110591488/183083283-9bd17f1a-643c-4ca9-8fd1-cbdca0d83376.png)
![36](https://user-images.githubusercontent.com/110591488/183083286-dda7c5a5-78e8-415b-a631-3969bf39cecf.png)
![37](https://user-images.githubusercontent.com/110591488/183083288-b4c45ab7-43ba-4a42-8dbe-be6c524cb07c.png)
![38](https://user-images.githubusercontent.com/110591488/183083297-d492be46-74f8-4835-b54c-c7eec06fd95b.png)
![39](https://user-images.githubusercontent.com/110591488/183083307-17251764-9512-4255-a928-aa419950914e.png)
![40](https://user-images.githubusercontent.com/110591488/183083312-955d9c36-e219-4174-8ed9-1815d81bc7fe.jpg)

**Comment by banned-historical-archives** [comment]
非语录、著作暂时不录进来吧？这类书籍到时另设一栏比较好？与普通文稿区分开

**Comment by 106coup** [comment]
@banned-historical-archives 可以挂一个待处理标签，以后再处理书籍

**Comment by banned-historical-archives** [comment]
#1260
