### ISSUE TITLE
红旗杂志录入进度

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#491]
https://bannedthought.net/China/Magazines/Hongqi/index.htm

- [x] 58
- [x] 59
- [x] 60
- [ ] 61 except 《关于机床内部矛盾问题的讨论》 in 24th.
- [ ] 62 except 22, 23, 24
- [x] 63
- [x] 64
- [x] 65
- [x] 66
- [x] 67
- [x] 68
- [x] 69
- [x] 70
- [x] 71
- [x] 72
- [x] 73
- [x] 74
- [x] 75
- [x] 76 1-10
- [x] 76 11-12

**Comment by PirateBook1** [comment]
红旗杂志放 archive2 吧，不要放 archive1，已经进来的这本也移动一下位置

**Comment by banned-historical-archives** [comment]
@PirateBook1 我们校对也分优先级吧，重要的文稿先校对，把多余的精力放在录入上面，普通文稿先不投入那么多精力了

**Comment by PirateBook1** [comment]
你说一些优先级

**Comment by PirateBook1** [comment]
我一直在录 Prolet 的造反派照片

**Comment by banned-historical-archives** [comment]
简单概括一下，越敏感的内容优先级越高

**Comment by PirateBook1** [comment]
搜索的问题是一定要解决的，即使是提供本地搜索方案。没有全文搜索功能，资料库的作用就废了一大半

**Comment by banned-historical-archives** [comment]
@PirateBook1 好的，我做一个本地搜索方案

**Comment by PirateBook1** [comment]
@banned-historical-archives 把书单和红旗录入完之后我打算开始去重工作了，Prolet 里还有一些人的讲话，不过都是中/右派的而非造派的了，优先级可以低一些，除了这些就剩下各种渠道的一大堆书，优先级又低了一些

**Comment by banned-historical-archives** [comment]
可以 @PirateBook1

**Comment by banned-historical-archives** [comment]
@PirateBook1  禁书优先录入，右派的文稿一般不是

**Comment by PirateBook1** [comment]
@banned-historical-archives 对了，或许你可以把全集给解析了，马列之声的全集是文字版的

**Comment by banned-historical-archives** [comment]
@PirateBook1 什么全集？

**Comment by PirateBook1** [comment]
@banned-historical-archives 马恩全集和列宁全集

**Comment by banned-historical-archives** [comment]
@PirateBook1 马恩全集和列宁全集似乎不算敏感内容，优先级可以低一点

**Comment by banned-historical-archives** [comment]
一九六二年的红旗缺少了第22、23、24期

红旗一九六一年第二十四期《关于机床内部矛盾问题的讨论》这篇文章缺失

**Comment by PirateBook1** [comment]
五八年第十三、五九年第二已录入

**Comment by PirateBook1** [comment]
已完成
