### ISSUE TITLE
王洪文同志在上海市机电一局系统活学活用毛泽东思想积极分子代表大会上的讲话（一九六八年三月十八日） 资源贡献

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#61]
![1](https://user-images.githubusercontent.com/110591488/183015713-6e762273-cfa2-4b2a-b0f9-5a0c92c250f9.png)
![2](https://user-images.githubusercontent.com/110591488/183015718-a8632abd-8a4c-4e84-94a0-51739e2d1a51.png)
![3](https://user-images.githubusercontent.com/110591488/183015720-636c1770-a514-48bb-acd7-88c3d8cb67f1.png)
![4](https://user-images.githubusercontent.com/110591488/183015724-e14a536f-e341-470f-a5a0-f51e9addafe1.png)
![5](https://user-images.githubusercontent.com/110591488/183015707-b76e3a0c-7917-45cf-b610-588e89e46902.png)

**Comment by PirateBook1** [comment]
上海市机电一局系统活学活用毛泽东思想积极分子代表大会
上市革会领导成员、工总司负责人王洪文同志的讲话

（根据录音整理，未经本人审查）

无产阶级革命派的战友们，革命的同志们：

首先让我们共同祝愿世界革命人民的伟大导师，中国人民的伟大领袖，我们心中最红最红的红太阳毛主席万寿无疆！万寿无疆！！万寿无疆！！！

在大好形势的凯歌声中，机电一局胜利召开了活学活用毛泽东思想积极分子代表大会，这是机电一局广大无产阶级革命派、革命职工的大喜事，也是全市革命人民的大喜事。这次大会的召开是广大无产阶级革命派、革命职工通过一年多来的文化大革命的总结，是个总结大会，誓师大会，也是全局的经验交流大会，是一年多来的两条道路、两条路线、两个阶级的大搏斗的伟大胜利，伟大标志！

我代表工总司向大会表示热烈祝贺，并借此机会向全局系统的无产阶级革命派致敬！

当前，全国无产阶级文化大革命形势大好，正如主席所指出的：“全国的无产阶级文化大革命形势大好，不是小好。整个形势比以往任何时候都好。”“再有几个月的时间，整个形势将会变得更好。”全国打得很厉害的地区，江西省革命委员会成立了，那里是第一个夺枪的单位，现在好得很，形势非常稳定。从新疆来看，原来以为是最落后的地区，现在转变得很快，目前正在考虑成立革命委员会的名单了。武汉曾是一度紧张的地区，后来陈再道揪出来了以后，百万雄师垮了台，形势现在也是很好，早就一片红了。河北省原来很落后，而一跃成为全国先进的地区。东北三省，去年只有黑龙江省成立了革命委员会，后来由于对群众组织处理不适当，出现了一个“跑轰派”，经过半年以来中央文革的工作，问题已经解决。吉林省本来很激烈，打得很凶，长春百货大楼打得一塌糊涂，现在吉林省、长春市都成立了革命委员会。只剩下了辽宁省，形势也大好。江浙两省现在也快要成立革命委员会了，无锡的形势也非常好，原“主力军”、“九二”势不两立，打得很凶。上二个礼拜，我去了无锡二次。上月17日去了一次，工矿企业大联合只有百分之二十五左右，百分之三十不到。第二次去是参加革命委员会成立大会，相隔十多天，一跃为百分之九十五以上。苏州原成立革命委员会，没搞大联合夺权，形成P派和G派，斗得凶，一个守在城内，一个守在城外，在中央达成协议，回来二天不到，就推翻了，后经春桥同志建议，把两派拉到上海，经过十多天的参观访问，在上海达成了协议。双方代表回苏州以后，全城欢腾迎接代表，双方都高呼学习的口号，原来是喊打倒什么派，现在是呼向什么派学习。镇江、常州形势也好，江苏省原定18日建立革命委员会，看来也没有啥大的变化，不会迟得太多。

剩下的广西、福建，据说广西正在酝酿名单。福建武斗已停止。

上海形势与全国一样也越来越好，第一个标志是活学活用毛泽东思想的群众运动从来没有象今天那样广泛、深入。前时期，广大无产阶级革命派都办了不同类型的学习班，有厂里办、车间办、小组办，还有街道办、里弄办，最近又发展到家庭办。办学习班，解决了大联合、三结合的问题，解决了不少关键问题，也逐步解决了许多老大难的问题。我们工总司第六期学习班，有32个单位，都是老大难的单位，学习了十一天，解决了30个单位，剩下2个单位，回家后也解决了。办学习班，现在越办越多，越办越好。解决了不少问题，改善了党群关系。通过学习班一系列问题都能解决。毛主席说：“办学习班，是个好办法，很多问题可以在学习班得到解决。”事实正是这样。通过学习班，推动了全市掀起活学活用毛泽东思想的新高潮。现在老人、青年、小孩都在学习毛主席指示，我住的那里小孩每天早晨起来背一、二个小时毛主席语录，边跑步、边背主席语录，原以为他们在吵闹，其实不然。这说明活学活用毛泽东思想的群众运动从来没有象今天那样深入、广泛，这是形势大好的第一个标志。

第二个标志是通过大办学习班、毛主席著作学习，促进了革命的大联合和三结合，并促进了斗、批、改。

通过“一月高潮”，全市百分之九十九的单位实现了大联合，百分之八十以上的单位建立了革命委员会，最近各单位、各系统、各区正进一步通过活学活用毛泽东思想积极分子代表大会和革命人民代表大会，巩固和发展革命大联合、三结合。

机电一局的形势也很好，全局423个厂，已有416个厂建立了革命委员会。271个较巩固，占64%；要进一步巩固的76个单位占18%；有个别单位，阶级阵线不清，占百分比之几；已经暴露出来、有严重问题的占4%。有武斗、有争吵的还有9个单位。因此形势也是大好。

第三个标志是阶级斗争胜利向前发展。阶级斗争的形势很快，全市各单位以整党建党为中心，清理阶级队伍的工作取得了很大的成效。有许多队伍原阶级斗争盖子未揭开，通过整党、建党，阶级斗争盖子揭开来了，过去混进了造反派的黑手，坏人已逐步揪出来了。当前，自从揪出李顺之、戚拯以后，南站又揪出了倪保华（音）、xxx（不清）以及朱长友一大批坏人。工总司内部，揪出了芦湾的贪污犯王保全，南总的强奸犯袁根林，化工的反革命分子张己华。通过阶级斗争的深入，把这些坏人都揪出来，清理出来，实行了无产阶级专政。

前段时期，总的形势是好的，发动了全市广大无产阶级革命派，揪出了一小撮隐藏的走资派、特务、叛徒。上次已讲了，最进还有发展，有些机关阶级斗争盖子正在一个个地被揭开，形势很好。

全市没解决的区已没有了，现在十个县，原建立革命委员会的有6个，最近又批准了一个。南汇、青浦、金山三个县也差不多了。南汇革命委员会名单正在讨论。社会秩序空前稳定，通过打击流氓阿飞、投机倒把，查封了驻沪办事处，革命秩序越来越好。

上海形势是大好的，但是还应该看到阶级敌人是不甘心失败的，还要垂死挣扎。目前出现的两种思潮，代表着社会反动势力。

一种是上锅厂以何是为代表的极右反动思潮。何是等一小撮反革命分子，把矛头对准中央文革、市革委会，长期干尽反革命勾当。何是只一个人，在厂内却大有市场。最近有人为他喊冤叫屈。有人认为保黄萍、倪绍康保对了。黄萍究竟是不是一个党员，还须调查。但这家伙，文化大革命以来支持一派，打击一派，几次武斗黄萍赤膊上阵。就凭这一点，就不该保。群众有许多材料上报了工总司。他所提出的二个介绍人就不承认他入过党。上次去锅炉厂开座谈会，群众揭发，二派武斗时，倪绍康讲打得好。群众问他“讲过吗？”他讲：“说的。”群众讲：凭这点我们就可叫你靠边。挑动武斗、制造分裂，还保他？倪绍康对何是反动思潮知道了不揭发、不开展批判、不斗争，而怂恿他们。这是一股反动思潮，斗争还在继续。

还有“中串会”印影版《红卫战报》登的“一切为了九大”是个彻头彻尾的反革命宣言书，要彻底批判。同志们！你们看到就能分析出，这决不是一个中学生能写出来的，很多措辞，不是中学生写得出的，这篇文章有他的社会背景。

在当前清理阶级队伍中阻力不小，包括机电一局。机电一局联络站头头黄胜亮，这个人是怎样的人物？本来不想多讲，现在还有人想保黄胜亮，就在此简单的讲一下。黄胜亮是个调到东北去的一个工人，不能吃苦，煽动工人回上海。长期来思想反动，他讲：“我就是要到台湾去。”“我就是要做反革命。”“国民党坏，一天能吃三顿饭，托共产党福，一天只吃三顿粥。”……。有人讲，我们对他的处理是资产阶级反动路线。如果的革命群众，运动中被打成反革命，那才叫是资产阶级反动路线。黄胜亮现在表现呢？不通过革委会私自发出公告，打一派，拉一派。我们找他说了以后，此人很狂妄，骂我是小事，竟还骂其他负责同志。松江武斗，他应该去制止武斗，但是他却调动人去搞武斗。后来张春桥指示：“这样做要犯错误。”黄胜亮竟说：“张春桥有什么了不起？”他目无法律，目无领导，目无无产阶级司令部。常熟武斗激烈时，他把国家的马达、电线送去给常熟去搞武斗。自己换肉换鱼，大吃大喝。再从黄胜亮组织的班子来看，他重用的人，有一部分人问题严重，流氓阿飞、反革命家属、思想反动的都受重用。机电一局联络站同志反映后，找他谈了，但问题一直解决不了。在忍无可忍的情况下，经常委会研究，派王腓利同志来主持这地方的工作。今天在座的各位同志都是积极分子，你们要关心总站的工作。

林付主席教导我们：领导班子就是政权，领导班子搞不好，我们的政权就很危险了。

我们在清理阶级队伍中，基层厂也发现这样一些情况：领导权被一小撮反革命分子和一小撮坏人掌握，对我们无产阶级专政，积极地进行反扑，有的把自己的档案烧掉了，有的把国家的机密档案抢了烧掉。这句话我们已经讲过了，这次我们再重复一遍，对于那些抢档案、烧档案的，还有那些专门找共产党员，革命干部进行打击的。这笔帐是要算的。（热烈鼓掌）（口号略）

最近我们又发现这样的一个单位，我刚才看了一个材料，觉得这个材料很重要，有这样一个小厂，造反派头头，外号叫什么“司令”这个家伙专门干坏事，我把这些事情讲一下吧！这个人自己开了汽车到杭州游山玩水，结果把汽车也翻到河滨里去了，回来既不修车也不检查，后来有的领导干部对他讲了一下后，他大发雷霆，“我是第一把手，我要掌权，我能掌权”，这样的话象一个无产阶级革命派吗？当我们召开了“贯彻中央《二·一八》紧急通知”大会后，有个同志讲这个大会很重要，他就讲：“xx算老几？”这个人在生活上也无耻到极点，还有一次打电话，大骂这个厂的领导干部。他还反对学习毛主席著作，谩骂张春桥同志，谩骂共产党员，他在看见群众学习老三篇的时候，他说什么“象老和尚念经”，在群众学习语录时，他说什么“成天读这么两句”，群众到上柴厂去学习，支持“东方红”他说：“张春桥为什么不能炮轰”他还骂厂里的党员说：“没有一个好的，都是娘子党员、资本家党员。”等等，人家说：“打倒刘少奇”他说：“我能做刘少奇就好了。”从这一系列问题我们可以看到阶级敌人是决不会甘心他们的失败的，千方百计地进行垂死的挣扎，他把骂人的这些话用录音机录下来，然后到他房间里去听，听了哈哈大笑，如果揭发的材料确实的话，应该把这个人揪出来，狠狠地给我斗（鼓掌），我们觉得上海形势大好，但是我们也经过不少阻力，阻力象十六条所讲到的那样：来自党内一小撮走资本主义道路的当权派，来自社会上的阶级敌人。所以我们还应该在大好形势下提高警惕，擦亮眼镜，把我们各个单位的阶级斗争盖子彻底揭开。

同志们，战友们：林付主席教导我们：“大海航行靠舵手，干革命靠毛泽东思想。”你们在一年多以来，在史无前例的无产阶级文化大革命中，活学活用毛主席著作，在抓革命，促生产，促工作中是个模范，希望你们通过大会的召开要戒骄戒躁，在今后的斗争中要不断地用毛泽东思想武装自己的头脑，改造我们的世界观。学习毛主席著作，就应该为世界革命而学，为世界革命而用。我们应该看到全世界还有三分之二的人民还没有解放。我们必须通过活学活用毛主席著作，来反对帝国主义、反对修正主义、反对各国反动派，为全世界被压迫人民、被压迫的民族的彻底解放而贡献出我们自己的力量。我们机电一局的广大无产阶级革命派和广大的革命职工，都担负着支援世界各国人民的重担，我们的许多产品都是出口援外的任务，希望担任这些任务的单位，在狠抓革命的基础上面把生产抓好，保证援外出口任务的胜利完成。我们今天学习毛主席著作，一方面要为世界革命而学，另外，学习毛主席著作要为夺权无产阶级文化大革命全面胜利学习，学习毛主席著作我们必须根据林付统帅的教导，要活学活用，学用结合，急用先学，立竿见影，在“用”字上狠下功夫，学一点用一点。林付主席还教导我们“学了不用，等于鬼话”那就是说：“我们学习就是应该用，你学了一句话，就用一句话，学了两句，就用两句”毛主席教导我们：“学习的目的全在于应用。”我们就是要边学边用。通过毛主席著作的学习，我们还必须紧紧掌握斗争的大方向，排除右的和极“左”方面的干扰，也包括当前社会上的两种反动思潮，我们应该给于这两种反动思潮狠狠反击，当然这两种反动思潮反下去以后还会出现新的反动思潮，阶级斗争是必然的，有的反动思潮打下去了，极“左”的还会出现，极“左”的思潮反下去了，右的又会抬头了，这是阶级斗争的规律，也没有什么了不起，只要我们保持清醒的头脑。上面分析当前的形势，出现了这种局面，怎么保持沉着一些，所以当前的形势看来，我们总觉得出现这样的反动思潮并不奇怪，不管怎么样，天塌不下来，以为文化大革命的局势早已经定了。通过当前毛主席著作的学习，出现了一个以整党建党为中心，狠抓阶级斗争，整顿了新的自己的阶级队伍，刚才我讲到了狠抓阶级斗争的几个例子，是几个典型的例子，从当前的形势来看，从机电一局的几个厂来看，也决不可以认为太平了，你比如一个有名的厂，我就不点名了，我们的局革会审批了专案小组的人员名单，但是厂却将他们全部靠边，换上有严重问题的人搞专案材料，这一个厂的头头请机电一局革命委员会审查一下，他是不是无产阶级革命派，他背后有没有人，他到底是什么派，前一个时候点过一次名，这一次就不点名了，他检查了自己不高举毛泽东思想伟大红旗，但没有检查到要害处，问题的要害是权掌握在什么人手里的问题，我们请局革会把这个批示送给他。我们还应该值得注意的是大家都很关心的上海汽轮机厂，上汽厂据我了解派了列席代表参加这次大会，希望这些同志回去传达我的意见：这个厂这么长时间以来，给我们国家带来多么大的损失，请造反派的头头算一笔账，很多人长期来，不参加生产，无政府主义泛滥，这些头头在抓些什么呢？希望这个厂的造反派头头回去检查一下，你掌权以后，给国家造成的损失。到现在这个厂还没解决，如果再继续下去，我们号召上海汽轮机厂的无产阶级革命派、广大革命职工起来造反，免掉这些头头，自己情起来闹革命。当然，象上汽厂这种问题也不是太多，极个别的。以为我们厂太多嘛，所以通过这次积极分子大会，大抓阶级斗争，根据毛主席的教导：“阶级斗争一抓就灵”应该狠抓、大抓、特抓，阶级斗争抓好了，就能带动各项工作，阶级斗争不抓，你想搞大联合，三结合，抓革命，促生产，那办不到，以为阶级敌人在搞破坏，你不抓阶级斗争怎么行啊！所以应该首先抓阶级斗争，这是一项很艰巨的工作，这一项工作上的阻力看来也是相当大的，希望各单位都能检查一下，自己单位的阶级斗争盖子揭开了没有，在这里要提到机电一局机关无产阶级革命派也应该检查一下，你们看一看机关的阶级斗争盖子是否揭开了，根据我们的看法及我们接到的材料，看来还有一段距离，还需要进一步发动群众，我们建议局革会与广大的无产阶级革命派一道广泛地反动群众把阶级斗争盖子自己揭开，把混进我们里面的叛徒、特务、走资派，统统把他们揪出来，只有这样才能把无产阶级文化大革命进行到底，只有这样才能巩固革命的大联合，革命的三结合，搞好抓革命，促生产，促工作，促战备，为夺取革命和生产的双胜利而努力奋斗，学习毛主席著作，还必须为实现人的思想革命化而学习，必须通过学习毛主席著作，努力地改造自己的世界观，都要狠斗一个“私”字，大立一个“公”字，树立一个“忠”字，使我们每个同志都能成为“一心为公”，永远忠于毛主席，永远忠于毛泽东思想，永远忠于毛主席的革命路线的坚强的战士，永远学习最高指示，宣传最高指示，捍卫最高指示的模范。同志们，战友们，我们相信，机电一局这次学习毛主席著作积极分子代表大会的召开，将会进一步推动全国的无产阶级文化大革命，将会使我们机电一局成为红彤彤的毛泽东思想大学校，使毛泽东思想的伟大红旗摇遍每一个阵地，我想乘机电一局召开活学活用毛泽东思想积极分子代表大会这一个机会，讲这么几点意见，同志们，由于我本身对毛主席著作学习得不够，毛泽东思想的伟大红旗举得不高，在讲话中间可能有缺点错误，希望同志们提出批评、帮助，另外今天这个大会，也是我学习的一个好机会，我愿意做同志们的小学生。最后让我们共同高呼：

读毛主席的书！听毛主席的话！照毛主席的指示办事！
做毛主席的好工人！
无产阶级文化大革命的全面胜利万岁！
毛主席的革命路线胜利万岁！
伟大、光荣、正确的中国共产党万岁！
光芒四射的毛泽东思想万岁！
我们伟大领袖毛主席万岁！万岁！万万岁！

一九六八年三月十八日
