### ISSUE TITLE
[自动化文稿录入]毛远新紧跟“四人帮”大反经验主义的部分罪行材料

### ISSUE THREAD

**Issue by PirateBook1** [banned-historical-archives/banned-historical-archives.github.io#662]
```
{
  source_name: '毛远新紧跟“四人帮”大反经验主义的部分罪行材料', // 来源文件名称，书籍，数据库，报纸等等
  archive_id: 1,
  articles: [{
    title: '一、毛远新紧跟“四人帮”大反经验主义的罪行',
    authors: ['毛远新'], // 作者
    page_start: 2,
    page_end: 3,
    ocr_exceptions: {
        "2": {
            content_thresholds: [0, 0, 0.5, 0],
        },
    },
    dates: [
      {
        year: 1975,
        month: 3,
        day: 5,
      },
      {
        year: 1975,
        month: 3,
        day: 31,
      },
      {
        year: 1975,
        month: 4,
        day: 3,
      },
      {
        year: 1975,
        month: 4,
        day: 10,
      },
      {
        year: 1975,
        month: 4,
        day: 15,
      },
      {
        year: 1975,
        month: 4,
        day: 22,
      },
      {
        year: 1975,
        month: 4,
        day: 23,
      },
      {
        year: 1975,
        month: 4,
        day: 24,
      },
      {
        year: 1975,
        month: 4,
        day: 25,
      },
      {
        year: 1975,
        month: 11,
        day: 26,
      },
    ],
  }, {
    title: '二、毛远新大反经验主义的言论（摘编）',
    authors: ['毛远新'], // 作者
    page_start: 3,
    page_end: 9,
    ocr_exceptions: {
        "9": {
            content_thresholds: [0, 0, 0, 0.5],
        },
    },
    dates: [
      {
        year: 1975,
        month: 3,
        day: 5,
      },
      {
        year: 1975,
        month: 3,
        day: 31,
      },
      {
        year: 1975,
        month: 4,
        day: 3,
      },
      {
        year: 1975,
        month: 4,
        day: 10,
      },
      {
        year: 1975,
        month: 4,
        day: 15,
      },
      {
        year: 1975,
        month: 4,
        day: 25,
      },
      {
        year: 1975,
        month: 7,
        day: 16,
      },
      {
        year: 1975,
        month: 7,
        day: 17,
      },
      {
        year: 1975,
        month: 11,
        day: 26,
      },
    ],
  }, {
    title: '三、毛远新亲自修改的一份未发出的省委文件（大样）',
    authors: ['毛远新', '中共辽宁省委', '辽宁省革命委员会宣传组'], // 作者
    page_start: 9,
    page_end: 13,
    ocr_exceptions: {
        "9": {
            content_thresholds: [0, 0, 0.5, 0],
        },
        "13": {
            content_thresholds: [0, 0, 0, 0.5],
        },
    },
    dates: [
      {
        year: 1975,
        month: 4,
        day: 15,
      },
      {
        year: 1975,
        month: 4,
        day: 18,
      },
    ],
  }, {
    title: '四、毛远新授意发表的第二次理论讨论会的消息报道',
    authors: ['辽宁日报', '中共辽宁省委', '辽宁省革命委员会宣传组'], // 作者
    page_start: 9,
    page_end: 13,
    ocr_exceptions: {
        "13": {
            content_thresholds: [0, 0, 0.5, 0],
        },
    },
    dates: [
      {
        year: 1975,
        month: 4,
        day: 22,
      },
    ],
  }]
}
```
![毛远新1975年批经验主义问题的部分材料节录01](https://user-images.githubusercontent.com/113572850/197324189-44150300-0659-4a27-81e0-628cdda0d121.png)
![毛远新1975年批经验主义问题的部分材料节录02](https://user-images.githubusercontent.com/113572850/197324190-e23718ae-1754-44de-b62b-11876cebab4f.png)
![毛远新1975年批经验主义问题的部分材料节录03](https://user-images.githubusercontent.com/113572850/197324191-ef3321be-b6fc-411c-8723-3406e1b38642.png)
![毛远新1975年批经验主义问题的部分材料节录04](https://user-images.githubusercontent.com/113572850/197324192-93c28acd-24a2-4962-b498-f5f2b880da0c.png)
![毛远新1975年批经验主义问题的部分材料节录05](https://user-images.githubusercontent.com/113572850/197324194-300d63dd-ff04-4538-849e-c35cb39474ab.png)
![毛远新1975年批经验主义问题的部分材料节录06](https://user-images.githubusercontent.com/113572850/197324195-fada29bd-d44c-4f12-b05f-3dc657ee00a7.png)
![毛远新1975年批经验主义问题的部分材料节录07](https://user-images.githubusercontent.com/113572850/197324196-e2735a0f-cfa6-41b1-845c-984eaddedec5.png)
![毛远新1975年批经验主义问题的部分材料节录08](https://user-images.githubusercontent.com/113572850/197324199-68bf001d-c284-4483-b802-7a2bef14e51f.png)
![毛远新1975年批经验主义问题的部分材料节录09](https://user-images.githubusercontent.com/113572850/197324201-75927b3b-5f5d-43e0-9bf7-0c7c5c89ba2f.png)
![毛远新1975年批经验主义问题的部分材料节录10](https://user-images.githubusercontent.com/113572850/197324203-2d847673-8f40-4861-8a9e-a5fc8301bb48.png)
![毛远新1975年批经验主义问题的部分材料节录11](https://user-images.githubusercontent.com/113572850/197324204-dda87e49-3363-427e-94de-f25e707aa3e2.png)
![毛远新1975年批经验主义问题的部分材料节录12](https://user-images.githubusercontent.com/113572850/197324205-b36d1e4d-5ed4-4008-a2e4-a5d0942ee9d0.png)
![毛远新1975年批经验主义问题的部分材料节录13](https://user-images.githubusercontent.com/113572850/197324206-a4095645-de92-4c90-97de-6e9d4094c296.png)
![毛远新1975年批经验主义问题的部分材料节录14](https://user-images.githubusercontent.com/113572850/197324241-93147749-d609-42a7-b88c-b312b8b276d0.png)
![毛远新1975年批经验主义问题的部分材料节录15](https://user-images.githubusercontent.com/113572850/197324844-054209bf-98d4-4097-8edc-e3c615bc151a.png)

**Comment by PirateBook1** [comment]
@banned-historical-archives 顺便帮忙看看 ocr_exceptions 可以这样加吗

**Comment by PirateBook1** [comment]
@banned-historical-archives 这里的 OCR 参数看起来并没有生效

**Comment by PirateBook1** [comment]
@banned-historical-archives

**Comment by PirateBook1** [comment]
这里的 ocr_exceptions 可以这样加吗

**Comment by PirateBook1** [comment]
是不是每个 articles 都有自己的 ocr_exceptions

**Comment by banned-historical-archives** [comment]
不行，只能在最外层

**Comment by banned-historical-archives** [comment]
好像放里面也很合理

**Comment by PirateBook1** [comment]
但是并没有起效

**Comment by PirateBook1** [comment]
@banned-historical-archives https://banned-historical-archives.github.io/articles/8203c9ef25/

**Comment by banned-historical-archives** [comment]
我没这么设计，目前只有最外层的ocr_exceptions才生效

**Comment by PirateBook1** [comment]
看这个文稿，我想过滤掉左半边的文字

**Comment by PirateBook1** [comment]
第九页左半边

**Comment by banned-historical-archives** [comment]
我等下加上这个配置

**Comment by banned-historical-archives** [comment]
@PirateBook1 https://banned-historical-archives.github.io/articles/8203c9ef25/
已经生效
