### ISSUE TITLE
杂志/书籍系列名称 以及 书籍类型

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#671]
书籍名称太过具体，不方便检索
例如：红旗一九六六年第一期。。。第八期
毛泽东全集第一卷。。。第五十二卷

书籍中应该再加一个字段 比如collection_name

另外应该增加一个书籍的类型，比如book_type，可选类型包括magzine，history, theories

**Comment by banned-historical-archives** [comment]
@PirateBook1 如何？

**Comment by PirateBook1** [comment]
就目前的情况我感觉暂时没必要，比如要搜红旗某年某期的，就直接搜红旗，然后再根据现有的格式比如红旗一九六六年第一期再照葫芦画瓢搜索

问题在于录入要维持格式，红旗一九六六年第一期

有做一个模糊搜索的可能吗，如果有模糊搜索的可能连录入格式这个也不必要了

**Comment by banned-historical-archives** [comment]
@PirateBook1 怎样模糊搜索？1966和一九六六自动转换？

**Comment by PirateBook1** [comment]
@banned-historical-archives 先开发表格插图的功能吧

**Comment by banned-historical-archives** [comment]
待定
