### ISSUE TITLE
进一步使用深度学习辅助文稿录入

### ISSUE THREAD

**Issue by banned-historical-archives** [banned-historical-archives/banned-historical-archives.github.io#701]
(中长期目标）

第一阶段，插图和表格检测模型，检测出大概的包围盒，截图作为一个特殊的段落类型录入文稿。

第二阶段，
已OCR校对的数据作为训练数据，训练新的识别模型，提高识别率；
因为校对结果已经没有“换行”的概念，文本对应的图片原始坐标也不好映射回去了。
仅训练 校对的段落中变化的文本总数小于3的段落中的文本。（这种情况基本上能找到对应文本的坐标）

第三阶段，训练段落识别模型（暂时没什么思路），是否可以利用已校对的数据去训练？

**Comment by banned-historical-archives** [comment]
@PirateBook1 插图的人工维护工作量很大，先有自动化识别工具，再人工校对比较好

**Comment by banned-historical-archives** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/dataset/table_datasets_en.md
或者支持简单的表格OCR（转成Markdown之类的存进数据库），应该比转换为插图要好

**Comment by PirateBook1** [comment]
第一阶段的开发可以现在就开始，应该相对容易吧？后面第二第三阶段要不要这样弄，再想一下

**Comment by PirateBook1** [comment]
> https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/dataset/table_datasets_en.md 或者支持简单的表格OCR（转成Markdown之类的存进数据库），应该比转换为插图要好

我觉得，干脆将一切非文字的表格、图表、图片这类的全部归到一起，再不要单列出来了

**Comment by banned-historical-archives** [comment]
@PirateBook1 我现在还有些别的事情，你有空的话可以帮忙弄一下

**Comment by PirateBook1** [comment]
我哪懂得啥深度学习，太抬举我了

**Comment by banned-historical-archives** [comment]
@PirateBook1 是的，需要长期维护。其实我也不懂深度学习，但我知道看起来高级的技术绝不是资产阶级知识分子的专利，想学都能学得会学得好，去学习它也是对这刻板思维的斗争。

**Comment by banned-historical-archives** [comment]
![图片](https://user-images.githubusercontent.com/109972625/198332222-360a6c8f-b556-4006-a149-b5d1d298412f.png)

书法图片被误判为标题

**Comment by banned-historical-archives** [comment]
根据上面的测试结果，可以使用paddle structure 提取插图，提取表格。并且使用它的text框，改进段落合并策略。

完全自动化录入不太可能，不过可以利用paddle structure半自动提取标题(然后手动校对标题和页码范围），也节省很多工作量了。

**Comment by PirateBook1** [comment]
部署查看效果吧

**Comment by hubred-rev** [comment]
個人家庭GNU/Linux使用Paddle OCR時需要限制輸入圖片的Paddle OCR大小，否則nouveau會報錯導致系統重啟。

**Comment by banned-historical-archives** [comment]
@hubred-rev 可能需要4G以上的内存？

**Comment by hubred-rev** [comment]
> @hubred-rev 可能需要4G以上的内存？

需要内存，也需要显存。

**Comment by hubred-rev** [comment]
> @hubred-rev 可能需要4G以上的内存？

主要是Image、OpenCV等等这些Python模组最吃显存，Paddle OCR也可能吃一部分显存；此外就是驱动不能使用nouveau，这也就导致只能使用不自由的软件来使用Paddle OCR。Paddle OCR整体来说是不自由的软件。

**Comment by hubred-rev** [comment]
> @hubred-rev 可能需要4G以上的内存？

Debian/Ubuntu都可以，但是GNU.ORG上所有的操作系统都不行，因为他们使用nouveau。

**Comment by hubred-rev** [comment]
> @hubred-rev 可能需要4G以上的内存？

以上只是论述了保证稳定使用的条件，此外，图片的文件大小也是决定系统会不会崩溃的关键，如果图片超过1.5MB系统内核就有可能崩溃（nouveau报错无法初始化组件），可以前往Linux内核查看崩溃记录，我的显卡是GTX1050TI，也许别人会有不一样的结果。

**Comment by hubred-rev** [comment]
> @hubred-rev 可能需要4G以上的内存？

使用最新版本的私有的显卡驱动。

**Comment by PirateBook1** [comment]
@banned-historical-archives 第二第三阶段的目标没有头绪吗
