### ISSUE TITLE
王洪文同志在沪东造船厂发动群众对敌斗争现场会上的讲话（一九六八年一月五日）

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#81]
![1](https://user-images.githubusercontent.com/110591488/183047054-818034b7-eb91-4549-8f59-0f7aee8ea015.jpg)
![2](https://user-images.githubusercontent.com/110591488/183047064-d191c6ce-048e-40bb-b87e-47136344230b.jpg)

**Comment by 106coup** [comment]
@banned-historical-archives 

王洪文在沪东造船厂发动群众对敌斗争现场会上的讲话

1975.1.14

一、进一步放手发动群众

当前对敌斗争形势大好，斗争在深入发展，还要进一步放手发动群众，挖出的敌人，质量都很高，群众政策水平有很大提高。有些单位群众发动得不那么好，要进一步用党的政策武装和发动群众。

二、只有用党的政策武装和发动群众，才能进一步团结一切革命力量，稳、准、狠地打击一小撮阶级敌人

把政策和发动群众对立起来的观点是错误的，要严格区分两类不同性质的矛盾，严格区分主要矛盾和次要矛盾，不分清这些就不能胜利，就会给革命造成损失。中央两报一刊七一社论指出，“要始终把斗争矛头对准一小撮顽固不化的走资派、叛徒、特务以及没有改造好的地富反坏右分子”，工总司5·5扩大会议纪要中提出了这个问题有几个“严格区分”，特别是文化大革命中表现好与不好要严格区别。

有的把矛头不指向敌人，而热衷于处理男女关系、小偷小摸，男女关系、小偷小摸这些问题是要在经常工作中帮助教育的，不是这次运动的对象，对这些人要做思想工作帮助他们，对男女关系非常感兴趣的人本身思想就不健康，对于一般的国民党员、三青团员、护工队员，交代清了的，运动中不干坏事的，要教育他们不要有顾虑，更不许打击他们，对于表现不好的当然要打击。

敌人毒辣的手段是故意混淆两类不同性质的矛盾，矛头指向有一般政治历史问题的人，搅乱阶级阵线，我们必须针锋相对，严格区分两类不同性质的矛盾，能否善于处理人民内部矛盾，是能否团结大多数的很重要的问题，如果去年一月狠狠打击了赤卫队员，可以想象今日上海的局面，由于我们遵循了毛主席的教导，就团结了极大多数，现在仍然应该团结大多数，打击的对象应是百分之几，干部和群众95%都是好的和比较好的，这样才能深入开展运动，稳、准、狠地打击一小撮阶级敌人。

沪东厂做后进工作者的经验，对每个同志都有启发。如正确对待一个做过妓女的，这很能说明问题，如整了这个人很可能有反革命就挖不出，有历史污点的人顾虑较多，有一个人想交待政历上的严肃问题，又不敢，因为他单位里打人很厉害，有政历问题的人往往是知情人，是敌人与我们争夺的对象，如果我们不争取他，敌人就要争取他，有的敌人压制他们交代问题，要帮助他们放下包袱，使敌人害怕。

三、利用矛盾，区别对待，争取多数，反对少数，各个击破

对敌人也要一分为二，它不会是铁板一块，要善于发挥党的政策的威力，分化瓦解他们，首恶必办，胁从不问，立功受奖，坦白从宽，抗拒从严，不要一概而论，凡是有问题的都打击，那就不对了，沪东厂是榜样，有的单位不按政策办事，狠斗、游街、排队示众，看的人说：“你们干什么？搞动物园吗？”这解决不了问题，如果一律对待，不加以区别，有利于敌人，不利于我，要学习新华厂。

依靠广大人民群众，加强无产阶级专政，这是一个问题的两个侧面，离开了群众，专政就谈不上加强，对敌斗争就谈不上胜利，侧重点还是发动群众，依靠群众。

有人企图扩大打击面，破坏革命委员会与群众的联系，阶级敌人从而蒙混过关，我们要坚决依靠无产阶级革命派，依靠群众，毫不动摇，我们要打击一小撮死不混改的走资派、叛徒、特务、没有改造好的地富反坏右分子。这些人，就是国民党残渣余孽，除此之外，没有别的国民党残渣余孽了，这一小撮人代表了蒋匪在大陆上的利益，这只能是一小撮，所以称之为残渣余孽，另外去找残渣余孽，就会把一般问题的人带进去。

搞清楚了依靠谁，打击谁，革命委员会就掌握了大方向，就得到群众的支持，革委会就巩固发展。这是关系到无产阶级专政的前途和命运的大事。革命委员会巩固的过程，就是严肃的阶级斗争过程。破坏革命委员会有种办法：一是削尖脑袋钻进去；一是破坏革命委员会与群众的联系，清除了这些，革命委员会就朝气蓬勃。

不断学习群众，这是七一社论的要求，新老干部一样要继续总结群众的经验，加以推广，革命小将、新干部，一定要谦虚谨慎。学习群众，学习老干部，学习解放军，革委会吸取这样的革命小将，一定朝气蓬勃非常有生命力。

联系群众不是一天到晚拉家常，是用毛泽东思想武装群众。沪东厂大办毛泽东思想学习班，巩固和发展了革命大联合，三结合，学习班要随时跟着群众运动的发展增加新的内容，这是七一社论提出来的。邮电系统对敌斗争近来很有起色，重要的原因是解放军在那里大办学习班。

对敌斗争，清理阶级队伍，根本目的不在于挖出一小撮国民党残渣余孽，完事如果只满足于故事，多多益善，越大越好，那又怎么样呢？根本目的是要铲除复辟基础，改造世界观，杜绝和防止修正主义，使党不变质，国家不变色。因此，一定要和革命的大批判、整党、本单位斗批改结合起来，那批坏蛋不可能在工交战线上推行修正主义路线。

（记录稿，仅供参改）

**Comment by banned-historical-archives** [comment]
赞！

**Comment by banned-historical-archives** [comment]
时间是68年7月还是1月？文字版又是1975.1.14

**Comment by 106coup** [comment]
@banned-historical-archives 那个日期从论坛复制的时候复制错了，一切以文稿为准。

**Comment by banned-historical-archives** [comment]
https://banned-historical-archives.github.io/articles/3f77aa6b2d/
