### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#93]
我这边好像没法给 issue 加标签，请问能否给个相关权限？协作者之类的。

**Comment by banned-historical-archives** [comment]
给你加了权限，我们现在可以互相审核Pull request

**Comment by 106coup** [comment]
@banned-historical-archives 搜索功能有问题。

![1](https://user-images.githubusercontent.com/110591488/183094866-6d42fa98-0d16-4f93-88ec-481b9f25db74.png)
搜索文章标题，没有结果。

**Comment by banned-historical-archives** [comment]
要等谷歌收录。没那么快的。

**Comment by 106coup** [comment]
@banned-historical-archives 我看部署 log 里面发现有很多文章是异型日期，恐怕这个也得抽时间处理一下。

**Comment by banned-historical-archives** [comment]
这些是warning，没大问题。有些文章日期不规范，可能放在第一段或者最后一段，所以我进行了一些尝试。

**Comment by 106coup** [comment]
@banned-historical-archives https://banned-historical-archives.github.io/articles/3d56bd28eb/
校对次数恐怕还有问题，看这篇文章的校对次数。

**Comment by 106coup** [comment]
@banned-historical-archives 

两个问题：
1. 校对的时候一篇文章错误太多，生成的代码太长，拉不上 Github。
https://banned-historical-archives.github.io/articles/3d56bd28eb/
![image](https://user-images.githubusercontent.com/110591488/183275950-c757d5f3-929b-4b21-9b7b-23552ec92c1e.png)

2. 原稿里各种文字格式，比如说加粗怎么校对？直接在校对模式里使用 markdown 语法？

**Comment by banned-historical-archives** [comment]
1. 代码太长的情况，我准备加个导出代码按钮，用户手动复制到issue
2. 加粗/颜色等样式问题应该不用管吧？记录稿是从声音转换成的文字，本身不包含任何样式信息。段落信息还是能听出来的。

**Comment by 106coup** [comment]
@banned-historical-archives 上传到系统的时候应当注意重复问题，待处理的一些文章与系统里文章已经存在重复了。

**Comment by banned-historical-archives** [comment]
第2点是什么情况？

**Comment by 106coup** [comment]
@banned-historical-archives 

![image](https://user-images.githubusercontent.com/110591488/183292906-52bdfc95-88fd-40bf-a613-c45eb7aafa7c.png)
![image](https://user-images.githubusercontent.com/110591488/183292913-13d2b7d8-d8a8-4c2e-8c3e-df09faeb6d7b.png)

**Comment by banned-historical-archives** [comment]
那我在wiki中补充一下

**Comment by banned-historical-archives** [comment]
时间筛选器和代码太长的问题已经修复，正在部署
