### ISSUE TITLE
王洪文副主席在接见总参民兵组训工作座谈会议全体同志时的讲话（根据记录整理）（一九七四年九月二十二日）

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#95]
![1](https://user-images.githubusercontent.com/110591488/183079298-ad78f30c-19df-4fa9-9884-02588da6248e.png)
![2](https://user-images.githubusercontent.com/110591488/183079302-fb11122b-363c-44e0-9f4d-272b53807865.png)
![3](https://user-images.githubusercontent.com/110591488/183079266-be358c44-a390-499a-942b-5ceced4740a6.png)
![4](https://user-images.githubusercontent.com/110591488/183079278-b4f75449-3d6e-462f-896f-1a88a2423507.png)
![5](https://user-images.githubusercontent.com/110591488/183079284-17e5a7be-354f-419b-94d4-41674fe93028.png)
![6](https://user-images.githubusercontent.com/110591488/183079287-5dee692d-3091-4b9e-b4f7-a9452db68291.png)
![7](https://user-images.githubusercontent.com/110591488/183079295-503d7422-7a74-43fb-b84d-567576c19f59.png)

**Comment by banned-historical-archives** [comment]
#404
