### ISSUE TITLE
张春桥王洪文同志在上海市革命委员会研究工代会上讲话的会议记录（一九六七年十一月二十二日）

### ISSUE THREAD

**Issue by 106coup** [banned-historical-archives/banned-historical-archives.github.io#99]
![1](https://user-images.githubusercontent.com/110591488/183087650-33373fa7-dc90-4753-b0e3-7381ee75b34c.jpg)
![2](https://user-images.githubusercontent.com/110591488/183087656-d22360aa-58fe-4d83-8b9f-c925162a8190.jpg)
![3](https://user-images.githubusercontent.com/110591488/183087509-98ee1735-d9bc-4a7d-84d7-b2d8dba24cfa.jpg)
![4](https://user-images.githubusercontent.com/110591488/183087553-4453442c-08cd-4f40-b314-c1a651dcb96a.jpg)
![5](https://user-images.githubusercontent.com/110591488/183087568-afb17cfd-71bd-4505-a3d3-024452a15912.jpg)
![6](https://user-images.githubusercontent.com/110591488/183087578-a9840f75-dacd-4ba1-ad3b-7ef57d7a4c6b.jpg)
![7](https://user-images.githubusercontent.com/110591488/183087591-7f552d44-ade3-4d10-a94f-e8523e32691d.jpg)
![8](https://user-images.githubusercontent.com/110591488/183087604-6a3ae3b4-18d1-49fb-bd2b-5b2229588162.jpg)
![9](https://user-images.githubusercontent.com/110591488/183087615-136f4286-2778-461f-b7b6-91dc0b571464.jpg)
![10](https://user-images.githubusercontent.com/110591488/183087627-75574b5e-7fd3-4494-a975-d9574ff67fe4.jpg)
![11](https://user-images.githubusercontent.com/110591488/183087640-7cbea8d5-b425-4563-a993-d20db757a72c.jpg)

**Comment by banned-historical-archives** [comment]
#408

**Comment by banned-historical-archives** [comment]
#409
